### ISSUE TITLE
reproducibility of neighborhood generation

### ISSUE THREAD

**Issue by bjstewart1** [MarioniLab/miloR#105]
Can you add a set.seed for `makeNhoods` 
Repeat runs generate different results.
set.seed() globally doesn't seem to fix this.

**Comment by MikeDMorgan** [comment]
`set.seed` should only be set by the user - setting within functions can have unintended consequences. See:
https://www.bioconductor.org/developers/package-guidelines/

Can you post a reproducible example, i.e. identical input and `set.seed`, but with different results?

**Comment by bjstewart1** [comment]
> `set.seed` should only be set by the user - setting within functions can have unintended consequences. See:
> https://www.bioconductor.org/developers/package-guidelines/
> 
> Can you post a reproducible example, i.e. identical input and `set.seed`, but with different results?


Here is an example:




Do let me know if I'm doing something obviously wrong
[Reprod example.pdf](https://github.com/MarioniLab/miloR/files/5880508/Reprod.example.pdf)

**Comment by MikeDMorgan** [comment]
Thanks - can I ask you to check if you get the same output for `runif(5)` before and after the `buildGraph` step?

**Comment by bjstewart1** [comment]
short answer is no. Posted below. 
[Reprod example.pdf](https://github.com/MarioniLab/miloR/files/5880572/Reprod.example.pdf)

**Comment by MikeDMorgan** [comment]
OK, try setting the seed before the for loop as well, after the call to `buildGraph`.

**Comment by bjstewart1** [comment]
Interestingly - before for loop get different results.
Directly before the `makeNhoods` function in the for loop getting identical results.

Thanks for helping troubleshoot this.
It makes me a bit nervous that set.seed() seems so fragile :/
So I will set the seed again directly before  `makeNhoods` and hopefully that will fix. Any idea what underlies this behaviour?
[Reprod example.pdf](https://github.com/MarioniLab/miloR/files/5880631/Reprod.example.pdf)

**Comment by MikeDMorgan** [comment]
Glad that fixed it. I'm not sure tbh - random number generators are fairly complex by the sounds of things:
https://stackoverflow.com/questions/13997444/print-the-current-random-seed-so-that-i-can-enter-it-with-set-seed-later/27672096

**Comment by bjstewart1** [comment]
much obliged. thanks for your assistance. Might be an idea to test this on the vignettes?
