### ISSUE TITLE
Error in makeNhoods when using KNN graph built by scanpy

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloR#107]
Running from the [vignette](https://github.com/MarioniLab/milo_analysis_2020/blob/master/notebooks/milo_in_python.ipynb):
```r
milo_graph <- buildFromAdjacency(knn_adjacency, k=k, is.binary=TRUE)
graph(milo) <- milo_graph@graph$graph

milo <- makeNhoods(milo, prop = 0.1, k = 30, d=30, reduced_dims = "PCA")
```
I get:
```
Error in replCmat4(x, i1 = if (iMi) 0:(di[1] - 1L) else .ind.prep2(i,  : 
  too many replacement values
```

Works perfectly if I run
```
milo <- buildGraph(milo, k=30, d=30, reduced.dim = "PCA")
milo <- makeNhoods(milo, prop = 0.1, k = 30, d=30, reduced_dims = "PCA")
```

**Comment by MikeDMorgan** [comment]
I haven't had a chance to delve into this, but it looks like it's coming from `Matrix`. I occasionally get some weird indexing warnings, the source of which is a bit of a mystery. Can you pin down where in `makeNhoods` this error comes from, i.e. what is the full traceback?

**Comment by MikeDMorgan** [comment]
Can we consider this issue resolved now?
