### ISSUE TITLE
Dependency on Matrix > 1.3

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloR#112]
Running `countNhoodDistance` with installed Matrix < 1.3 throws an error, because of missing `repr` parameter in old version of sparse matrix https://github.com/MarioniLab/miloR/blob/e907431f25e40ef66cc3c2e13a5c8284a0e04d44/R/calcNhoodDistance.R#L100-L102
Is it safe to add `Depends: Matrix > 1.3` to the `DESCRIPTION`? Or is the `repr` option disposable?

**Comment by MikeDMorgan** [comment]
We could have a version check and pass either `Csparse=TRUE/FALSE` (Matrix < 1.3) or `repr="T/C"` (Matrix >= 1.3). This isn't the only function that instantiates a `sparseMatrix`, so it would need to apply to all of them. We could as you suggest just enforce a minimum version of Matrix.

If we enforce a minimum version of Matrix, then I think we need to treat this as a version change for `miloR` as well, and bump it to 0.2, as well as include a record of the relevant changes.

**Comment by MikeDMorgan** [comment]
See PR #117

**Comment by emdann** [comment]
thanks Mike!

**Comment by MikeDMorgan** [comment]
Real fix will be in #119
