### ISSUE TITLE
No man pages found in package  ‘miloR’

### ISSUE THREAD

**Issue by pascaltimshel** [MarioniLab/miloR#114]
I cannot access any man pages for miloR:

``` r
library(miloR) 
#> Loading required package: edgeR
#> Loading required package: limma
?makeNhoods
#> No documentation for 'makeNhoods' in specified packages and libraries:
#> you could try '??makeNhoods'
?testDiffExp
#> No documentation for 'testDiffExp' in specified packages and libraries:
#> you could try '??testDiffExp'
```

It seems like you have not enabled the man pages for the package. It would make it easier for users if don't have to open a browser and go to https://marionilab.github.io/miloR/.

I used `devtools::install_github("MarioniLab/miloR")` to install miloR, where I also get the message: `No man pages found in package  ‘miloR’`
```
Installing package into ‘/opt/projects/user/renv/library/R-4.0/x86_64-pc-linux-gnu’
(as ‘lib’ is unspecified)
* installing *source* package ‘miloR’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Creating a new generic function for ‘graph’ in package ‘miloR’
Note: possible error in 'sparseMatrix(i = all.dists$i, ': unused argument (repr = "C") 
Note: possible error in 'sparseMatrix(i = dist.df$rowIndex, ': unused argument (repr = "T") 
Goodbye at Thu Feb 18 11:02:35 2021

** help
No man pages found in package  ‘miloR’ 
*** installing help indices
** building package indices
Goodbye at Thu Feb 18 11:02:35 2021

** installing vignettes
** testing if installed package can be loaded from temporary location
Goodbye at Thu Feb 18 11:02:42 2021

** testing if installed package can be loaded from final location
Goodbye at Thu Feb 18 11:02:49 2021

** testing if installed package keeps a record of temporary installation path
* DONE (miloR)
Goodbye at Thu Feb 18 11:02:49 2021```

**Comment by emdann** [comment]
Hi @pascaltimshel, thank you for flagging this, something must have gone wrong in the latest build. I'm on it.

**Comment by MikeDMorgan** [comment]
It seems that `devtools::install_github()` doesn't build documentation that is generated with Roxygen (https://github.com/r-lib/devtools/issues/523), and is on-going issue. The solution for now would be to build locally to get the documentation built (with "--no-build-vignettes" for the moment as these are under development/flux).

We'll keep this open until we come up with a reasonable solution.

**Comment by MikeDMorgan** [comment]
Hi @pascaltimshel the man pages are now on the GitHub repo, so should appear with all installs using `devtools::install_github()`.
