### ISSUE TITLE
Mapping cells to (grouped) neighbourhoods

### ISSUE THREAD

**Issue by pascaltimshel** [MarioniLab/miloR#115]
hi @MikeDMorgan and @emdann,

I have a few questions regarding cell to neighbourhood mapping. I hope you can help me here...

### Q1: Mapping cells to neighbourhoods
**Q1**: Is it correct that this is the best (or only) way to the the cell ids for the neighbourhood_idx=14?
`colnames(milo)[milo@nhoods[,14]==1]`

### Q2: Mapping cells to grouped neighbourhoods
The [testDiffExp](https://marionilab.github.io/miloR/reference/testDiffExp.html) function merges adjacent neighbourhoods before performing DE analysis. My problem is there is no way of getting a cell-to-neighbourhood_group or neighbourhood-to-neighbourhood_group mapping for the results. 

As far as I can tell, you can get the cell-to-neighbourhood_group mapping when using`findNhoodMarkers(..., return.groups=TRUE). But in addition to this, it would be nice to get a neighbourhood-to-neighbourhood_group mapping.

**Q2A**: can you extend `testDiffExp` (and `findNhoodMarkers`) to return a cell-to-neighbourhood_group or/and neighbourhood-to-neighbourhood_group mapping?

**Q2B**: why are there 37 cells not in any of the grouped neighbourhoods? (see below example)

``` r
library(miloR)
#> Loading required package: edgeR
#> Loading required package: limma
data(sim_discrete)
milo <- Milo(sim_discrete$SCE) # 100 genes x 900 cells
milo <- buildGraph(milo, k=20, d=10, transposed=TRUE)
#> Constructing kNN graph with k:20
milo <- makeNhoods(milo, k=20, d=10, prop=0.3)
#> Checking valid object
meta.df <- sim_discrete$meta
meta.df$SampID <- paste(meta.df$Condition, meta.df$Replicate, sep="_")
milo <- countCells(milo, meta.data=meta.df, samples="SampID")
#> Checking meta.data validity
#> Counting cells in neighbourhoods
test.meta <- data.frame("Condition"=c(rep("A", 3), rep("B", 3)), "Replicate"=rep(c("R1", "R2", "R3"), 2))
test.meta$Sample <- paste(test.meta$Condition, test.meta$Replicate, sep="_")
rownames(test.meta) <- test.meta$Sample
da.res <- testNhoods(milo, design=~Condition, design.df=test.meta[colnames(nhoodCounts(milo)), ])
#> Warning in if (colnames(nhoodCounts(x)) != rownames(model)) {: the condition has
#> length > 1 and only the first element will be used
#> Performing spatial FDR correction withk-distance weighting
nhood.dge.markers <- findNhoodMarkers(milo, da.res, overlap=1, compute.new=FALSE, return.groups=TRUE)
#> Found 89 DA neighbourhoods at FDR 10%
#> Computing nhood adjacency
#> Nhoods aggregated into 3 groups
str(nhood.dge.markers)
#> List of 2
#>  $ groups:'data.frame':  863 obs. of  2 variables:
#>   ..$ CellID     : chr [1:863] "Cell1" "Cell2" "Cell3" "Cell4" ...
#>   ..$ Nhood.Group: num [1:863] 4 4 4 4 4 4 4 4 4 4 ...
#>  $ dge   :'data.frame':  100 obs. of  7 variables:
#>   ..$ logFC_4    : num [1:100] -2.81 -2.75 -2.69 -2.7 -2.74 ...
#>   ..$ adj.P.Val_4: num [1:100] 7.69e-235 1.29e-212 1.12e-209 7.35e-207 1.41e-204 ...
#>   ..$ logFC_3    : num [1:100] 2.41 2.36 2.41 2.39 2.38 ...
#>   ..$ adj.P.Val_3: num [1:100] 1.35e-174 1.59e-169 7.18e-169 6.90e-162 5.47e-159 ...
#>   ..$ logFC_2    : num [1:100] 0.474 0.404 0.365 0.361 0.365 ...
#>   ..$ adj.P.Val_2: num [1:100] 0.13 0.153 0.153 0.153 0.153 ...
#>   ..$ GeneID     : chr [1:100] "Gene27" "Gene75" "Gene61" "Gene14" ...
sum(!colnames(milo) %in% nhood.dge.markers$groups$CellID) # ---> 37 cells not in nhood.dge.markers
#> [1] 37
```
### Q3 (bonus): Example data for findNhoodMarkers
The example data for [findNhoodMarkers](https://marionilab.github.io/miloR/reference/findNhoodMarkers.html) documentation is not ideal, as the call to `findNhoodMarkers` results in `Warning: All graph neighbourhoods are in the same group - cannot perform DGE testing. Returning NULL`. 
**Q3**: It would make it easier for users if you updated the example data
```R
nhood.dge <- findNhoodMarkers(milo, da.res, overlap=1, compute.new=TRUE)
#> Found 37 DA neighbourhoods at FDR 10%
#> Calculating nhood adjacency
#> Nhoods aggregated into 1 groups
#> Warning: All graph neighbourhoods are in the same group - cannot perform DGE testing. Returning NULL
nhood.dge
#> NULL
```

**Comment by emdann** [comment]
Hi @pascaltimshel 

> Q1: Is it correct that this is the best (or only) way to the the cell ids for the neighbourhood_idx=14?
colnames(milo)[milo@nhoods[,14]==1]

Yes, do you think a getter would be useful in this case? 

> Q2A: can you extend testDiffExp (and findNhoodMarkers) to return a cell-to-neighbourhood_group or/and neighbourhood-to-neighbourhood_group mapping?

Yes we can and we will! We are preparing a refactoring where the grouping and the DGE testing will be separate functions, with intermediate objects stored (mentioned in https://github.com/MarioniLab/miloR/issues/103). This way the user can decide which neighbourhood groups to choose for DGE testing, which seems like the most practical solution in most use cases. 

> Q2B: why are there 37 cells not in any of the grouped neighbourhoods? (see below example)

We recently switched from building groups based on adjacency to using community detection (louvain). These might be in disconnected communities.

> Q3 (bonus)

Again, this is a leftover from the recent change in grouping algorithm. We should have checked the effect on the example in the vignettes more thoroughly.

Thanks for taking the time to sharing really useful feedback! As this is pretty much all work in progress we greatly appreciate this and we will prioritize this update

**Comment by pascaltimshel** [comment]
Thanks a lot for the really helpful replies!

**Q1**
> Yes, do you think a getter would be useful in this case?

Yes I think that would be useful, since such a function will end up in the documentation and hence make it easier for users to find.

**Q2A**
> Yes we can and we will! We are preparing a refactoring where the grouping and the DGE testing will be separate functions, with intermediate objects stored (mentioned in #103). 

This sounds like a great idea! Since I'm very interested in using this workflow for my current analysis, do you have a rough estimate on when a (beta) release will be ready?

**Q2B**
> We recently switched from building groups based on adjacency to using community detection (louvain). These might be in disconnected communities.

Can you elaborate on "These might be in disconnected communities"? I don't quite follow...
How can cells be disconnected communities (is that singleton clusters)? (And what does switching from adjacency to louvain mean for building groups? I accept if you don't have time to go into details here - I'm just curious)

**Comment by emdann** [comment]
> do you have a rough estimate on when a (beta) release will be ready?

No promises here, but certainly before the end of Feb

> How can cells be disconnected communities (is that singleton clusters)? (And what does switching from adjacency to louvain mean for building groups? I accept if you don't have time to go into details here - I'm just curious)

Bear in mind that here we are not clustering cells but neighbourhoods. We construct an adjacency matrix between neighbourhoods, counting how many cells they have in common (this is the same as computed by `buildNhoodGraph` and stored in `nhoodAdjacency(milo)`). Then the adjacency matrix is used for louvain community detection. 

In the previous version the neighbourhoods with concordant LFC and at least `overlap` cells in common where merged in the same group.

**Comment by pascaltimshel** [comment]
Thanks for the details - it makes better sense now! But let me try to get the last part I don't understand: what did you mean exactly by 'disconnected communities'? That is, why does some neighbourhoods not get assigned to groups? I thought louvain clustering would result in group/cluster assignment of all input observations (in this case neighbourhoods) - but maybe I'm wrong.
If I still don't follow, we will just leave it at that :-)

**Comment by emdann** [comment]
Hi @pascaltimshel
We have merged to master the new version of neighbourhood grouping + testing, you can find an example in the `milo_gastrulation` vignette.

wrt your questions

> what did you mean exactly by 'disconnected communities'? That is, why does some neighbourhoods not get assigned to groups?

This was happening because the pruning of edges based on overlap and direction of fold-changes was removing _all_ edges outgoing from some neighbourhoods. This will not be an issue with the new implementation.

Feel free to drop more feedback on the new grouping functions in a new issue!

**Comment by pascaltimshel** [comment]
Wonderful, you guys & girls are amazing
I look forward to testing it!
