### ISSUE TITLE
Invalid Class

### ISSUE THREAD

**Issue by StefanoBertoUTSW** [MarioniLab/miloR#121]
Hello! 

I have a little issue when I want to create a Milo object from a single cell experiment. 

the error I got is this: 
invalid object for slot "nhoodCounts" in class "Milo": got class "ddiMatrix", should be or extend class "matrixORMatrix"

I processed the data using Seurat and converted in SCE. 

Any suggestion? 
Thanks!

**Comment by emdann** [comment]
Hi @StefanoBertoUTSW 
Thanks for reporting this. I'm not sure when you installed the package, but could you try reinstalling with `devtools::install_github("MarioniLab/miloR")`? This used to be an issue, but `matrixORMatrix ` should now include `ddiMatrix` https://github.com/MarioniLab/miloR/blob/9dd209ce835de52595923e40e73c688f1b548c0a/R/AllClasses.R#L19-L20

**Comment by StefanoBertoUTSW** [comment]
Thanks! Worked! I thought it was a more complicated issue :-)
