### ISSUE TITLE
which cells are in a specific neighborhood?

### ISSUE THREAD

**Issue by ainarill** [MarioniLab/miloR#134]
Hi! Nice tool!
Just one question, is there any way to know which cells are in the neighborhoods? or in a specific group of neighborhoods?
Thank you so much!

**Comment by emdann** [comment]
Hi @ainarill 

Thanks for your interest. You are looking for the `nhoods` slot of the `Milo` object, that you can access with the getter `nhoods(milo)`. This stores a binary matrix where each row is a cell (i), each column is a neighbourhood (j) and the value of x_{i,j} indicates if the cell belongs to a neighbourhood (1 or 0).

As for the groups, the output to the function `groupNhoods` is a `data.frame` with the assignment of nhoods to groups in the `NhoodGroup` column. So if you want e.g. to find cells in neighbourhoods from group 1 you can do something like:
```
milo_res <- groupNhoods(milo, milo_res)
## Subset nhood matrix to nhoods of interest
gr1.nhood.mat <- nhoods(milo)[,milo_res$NhoodGroup == 1]
## Find cells in nhoods of interest
gr1.cells <- which(rowSums(gr1.nhood.mat) != 0)
```

Let us know if this helps!

**Comment by ainarill** [comment]
Perfect, thanks!

**Comment by friedue** [comment]
Following up on this excellently addressed question -- while following the code above I noticed that some cells have more than one neighborhood they're assigned to (i.e. `rowSums(milo) > 0`). Could you comment on the interpretation and ramifications of that? Are cells that belong to multiple neighborhoods shown as individual/independent dots in the beeswarm plots and so on?

**Comment by MikeDMorgan** [comment]
Hi @friedue There is no reason a cell cannot, or should not, belong to multiple neighbourhoods as these are not discrete groups like clusters. This was the motivation behind developing `Milo`, to get around this problem of assigning one cell to one cluster.

**Comment by friedue** [comment]
Absolutely, just goes to show that I really should have been reading the supplemental note of the paper. The mention of "overlap" in the vignette was definitely a clue as well.
