### ISSUE TITLE
findNhoodGroupMarkers() output

### ISSUE THREAD

**Issue by ainarill** [MarioniLab/miloR#135]
Hi,
The output of:
`nhood_markers <- findNhoodGroupMarkers(data_milo, data_res, subset.row = hvgs, 
                                       aggregate.samples = TRUE, sample_col = "sample")`
is a dataframe with the logFC and the adjusted p-values for the different groups of neighborhoods. The thing is that the rownames of this dataframe (that contain gene ids) and the column of GeneID generated don't match.

<img width="856" alt="Captura de pantalla 2021-03-16 a las 16 41 50" src="https://user-images.githubusercontent.com/44896796/111337604-845ecb80-8676-11eb-9317-627ed03d1b32.png">

Should they match? Does the information of logFC and the adj p-value correspond to the gene id in the column or in the rownames?

Thanks again!

**Comment by MikeDMorgan** [comment]
Hi @ainarill Thanks for flagging this - the code implicitly assumes that the results are in the same order, so I can only assume that one of the results dataframe is being reordered internally. For now I would stick with the rownames rather than the GeneID. I'll take a look and issue a fix for this.

**Comment by MikeDMorgan** [comment]
Hi @ainarill I've made a potential fix, which is now merged into the main repository (#136) - could you re-install from the repo and see if that fixes the problem? If not, would you mind sharing the inputs so that we can try to re-create the bug on our side.

**Comment by ainarill** [comment]
Hi @MikeDMorgan,
Now the output dataframe doesn't have a GeneID column, so the marker names are directly in the rownames, right?
Thank you so much!

**Comment by MikeDMorgan** [comment]
That's correct, I just want to double check that there are no warnings produced when you run this?

**Comment by ainarill** [comment]
No warnings! thanks a lot :)
