### ISSUE TITLE
Error when adding a precomputed KNN graph (buildFromAdjacency)

### ISSUE THREAD

**Issue by MartaCasado** [MarioniLab/miloR#144]
Hello! I am trying to add a precomputed KNN graph from Seurat with the buildFromAdjacency function, but I get the following error:

```
miloR::graph(data_milo) <- miloR::graph(buildFromAdjacency(data@graphs$RNA_snn, k=10))

Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'graph': missing value where TRUE/FALSE is necessary
 Warning message:
In nrow(x) * ncol(x) : NAs produced by exceeded integers.
```

Thanks!!

**Comment by MikeDMorgan** [comment]
Hi @MartaCasado Could you post your sessionInfo please, and the size of the input data set, i.e. how many rows and columns are there in `data`?

**Comment by MikeDMorgan** [comment]
OK, a couple of points. Your call is incorrect, it should be:
`miloR::graph(data_milo) <- buildFromAdjacency(data@graphs$RNA_snn, k=10)`

If you're building a graph with 54,152 cells I would strongly recommend a larger value of `k`, as with the current setup you will likely end up with very small neighbourhoods. We recommend choosing `k` such that k≥Sx5, where S is the number of experimental samples. Choosing a smaller value of `k` will increase resolution, but reduce power as the neighbourhood counts will be smaller and thus have a higher variance.

**Comment by MartaCasado** [comment]
Thank you @MikeDMorgan for the suggestion of increasing k. Yes, data_milo is already instantiated.

**Comment by MikeDMorgan** [comment]
Hi @MartaCasado what is the out put of `type(data@graphs$RNA_snn)`?

**Comment by MartaCasado** [comment]
```
> type(data@graphs$RNA_snn)
[1] "double"
```

**Comment by rtoddler** [comment]
Hi all,
Has this problem been solved? I have the same issue so I wonder if there is a solution.
Thanks!

**Comment by emdann** [comment]
Hi @rtoddler and @MartaCasado 
We have not been able to reproduce this error on standard Seurat objects. @rtoddler can you provide a bit more details on the data you are using e.g. dimensions?

**Comment by rtoddler** [comment]
Hi @emdann
The dimensions of the Seurat object is 22319 x 69062.

Here is the script I ran:
_data <- readRDS("data.rds") #load Seurat Object (processed by SCT, FindNeighbors and FindClusters)
data_sce <- as.SingleCellExperiment(data)
data_milo <- Milo(data_sce)
miloR::graph(data_milo) <- miloR::graph(buildFromAdjacency(data@graphs$SCT_snn, k=40)) #This dataset has 8 samples_

Here is the error I got:
_Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'graph': missing value where TRUE/FALSE needed
In addition: Warning message:
In nrow(x) * ncol(x) : NAs produced by integer overflow_

**Comment by emdann** [comment]
Thanks @rtoddler. Is `data@graphs$SCT_snn` binary? (i.e. contains only 0 and 1)

**Comment by rtoddler** [comment]
Hi @emdann 
I don't think so. In fact, I think it's a S4. Did I miss some steps here?
![SCT_snn](https://user-images.githubusercontent.com/62856645/113361182-fab72b00-9310-11eb-887c-3f936ce6c6af.png)

**Comment by MikeDMorgan** [comment]
Hi @rtoddler Sorry for the delay in responding here. The input to `buildFromAdjacency` should be a matrix, I'm not sure what the `Seurat::Graph` class is. Could you try converting it with `miloR::graph(data_milo) <- miloR::graph(buildFromAdjacency(as(data@graphs$SCT_snn, "dgCMatrix"), k=40))` perhaps?

**Comment by rtoddler** [comment]
Hi @MikeDMorgan It works!! Thank you so much. I really appreciate your help! I encounter another problem in the downstream however. I will open a new issue about it.

**Comment by MikeDMorgan** [comment]
Fab - glad that resolves the problem.
