### ISSUE TITLE
Any advice on 'priority' of adjusting parameters

### ISSUE THREAD

**Issue by zktuong** [MarioniLab/miloR#145]
Hi team, having lots of fun with this tool.

Can i ask if there's any general advice for the specifying the options for `k` and `proportion`?

For example, if i'm handling a small data set of sat about 2-3k cells, would it be preferable to decrease `k` to a small value first, or decrease `proportion` to a small value first? 

Also what about `d`? would you stick to the same `d` you'd use for general clustering/umap?

**Comment by MikeDMorgan** [comment]
Hi @zktuong 
I would recommend a smaller value of `k` indeed, maybe something k~20 or so. With a data set that small you can play around a bit with the parameters too. For the proportion, I'd say ~0.3 is fine, as it should capture most of the representative neighbourhoods pretty well.  W.r.t. `d` - for the sake of ease, stick with the same used for any other analyses. You can always plot the ordered eigenvalues for a PCA in a screeplot and look for the inflection, or use a jacknife approach to select the most significant PCs.

**Comment by zktuong** [comment]
Thanks!
