### ISSUE TITLE
Link for Basic Milo example on simulated dataset not working

### ISSUE THREAD

**Issue by pabloatria18** [MarioniLab/miloR#149]
Hello
I would tike to try this package but the Basic Milo example on simulated dataset link is not working

Thank you

**Comment by emdann** [comment]
Hi @pabloatria18, thanks for flagging this! While I fix it you can take a look at the [Mouse Gastrulation vignette](https://rawcdn.githack.com/MarioniLab/miloR/7c7f906b94a73e62e36e095ddb3e3567b414144e/vignettes/milo_gastrulation.html#5_Finding_markers_of_DA_populations) which demonstrates all the `miloR` functionality on a real dataset

**Comment by emdann** [comment]
Fixed by https://github.com/MarioniLab/miloR/commit/d2e6ca08bd81d340d9c1ac698863a2dfd5afa0e5
