### ISSUE TITLE
error in testNhoods sample names in design matrix and nhood counts are not matched

### ISSUE THREAD

**Issue by Marc-Benoit** [MarioniLab/miloR#150]
Thank you for all your hard work on this tool! I have been throwing an error running the testNhoods function. I have 6 samples, 3 replicates are controls and 3 replicates are transgenic (orig.ident = control1, control2, control3, tg1, tg2 and tg3). They are assigned as "control" and "tg" (ident = control, tg)

```
nuclei_design <- data.frame(colData(nuclei_milo))[,c('orig.ident', 'ident')]
nuclei_design <- distinct(nuclei_design)
nuclei_design

nuclei_milo <- calcNhoodDistance(nuclei_milo, d = 30)
da_results <- testNhoods(nuclei_milo,
                         design = ~ orig.ident,
                         design.df = nuclei_design)
da_results %>% 
  arrange(- SpatialFDR) %>% 
  head()
```
![image](https://user-images.githubusercontent.com/78891847/113618286-7375fa00-9625-11eb-9e10-564c91d36129.png)

Any help would be appreciated, thank you!

**Comment by Marc-Benoit** [comment]
As an update: after editing the rownames of nuclei_design to match 'orig.ident', it thows this error: 

![image](https://user-images.githubusercontent.com/78891847/113624415-9c01f200-962d-11eb-97ea-1deae4db4337.png)

**Comment by emdann** [comment]
Hi @Marc-Benoit, thanks for flagging this. Can I just make sure that you are using the latest version of the package, installed with `devtools::install_github("MarioniLab/miloR")`?

**Comment by Marc-Benoit** [comment]
Hi @emdann thanks for the reply! The version I am using is 0.99.6. I can get it to perform the analysis if I change `design = ~ orig.ident`  to `design = ~ ident`however I am unsure of how the dataframe relays the information of each cell. After performing `nuclei_design <- distinct(nuclei_design)` I lose the barcode information for each cell. I am very new to R and this type of analysis so I may be missing the point. Thank you for your patience! 

Before `distinct(nuclei_design)`
![image](https://user-images.githubusercontent.com/78891847/113723220-234b7600-96bf-11eb-9ebb-211efdcc9895.png)

After `distinct(nuclei_design)`
![image](https://user-images.githubusercontent.com/78891847/113723320-3bbb9080-96bf-11eb-879e-d3efd82dd54d.png)

**Comment by MikeDMorgan** [comment]
Hi @Marc-Benoit The `distinct()` function just creates a new data frame that contains only the set of rows with unique elements across the columns, hence it no longer provides single-cell information. The purpose of `design.df` argument is to portray the sample-level meta data that is used to perform DA testing. Hence, the rows should correspond to the different samples, and the columns should be the experimental variables of interest, namely the ones containinng the information which you wish to compare for DA testing.

**Comment by Marc-Benoit** [comment]
Hi @MikeDMorgan thank you! I understand now and have worked through to a solution. Appreciate all your help.

**Comment by mikyungjang** [comment]
hello, I installed miloR ver 1.0.0 yesterday (9/9/21) as 
`BiocManager::install("miloR")`
in Rstudio v1.4.1717 for Windows10. Bioconductor version 3.13 (BiocManager 1.30.16), R 4.1.0 (2021-05-18)
I followed the tutorial 1 today https://rawcdn.githack.com/MarioniLab/miloR/3646391023f600bae00efd9d940b888503d7a536/docs/articles/milo_demo.html
and got the same error as this issue subject at testNhoods();
`> da_results <- testNhoods(traj_milo, design = ~ Condition, design.df = traj_design)
Error in testNhoods(traj_milo, design = ~Condition, design.df = traj_design) : 
  Sample names in design matrix and nhood counts are not matched.
             Set appropriate rownames in design matrix.`

[sessionInfo.20210910.txt](https://github.com/MarioniLab/miloR/files/7145796/sessionInfo.20210910.txt)

I got the same error when I ran the tutorial code in RGui.
I wonder what caused this error.

**Comment by mikyungjang** [comment]
I also had same error when followed 'Example work flow' at the main page.
Assigning rowname before testNhoods() sorted the problem;
`rownames(traj_design)=traj_design[,"Sample"]`

I wonder whether there was problem loading data on my side. I literally copy and pasted tutorial code.

**Comment by MikeDMorgan** [comment]
Hi Both - the issue is a missing line in the vignette which will be updated in the next Bioconductor release. The error message tells you where the error is, i.e. that the rownames of `traj_design` don't match the sample names of `nhoodCounts(traj_milo)`. This is trivially fixed by setting `rownames(traj_design) <- traj_design$<name of sample column>`

**Comment by A-legac45** [comment]
Hello, I am trying to use Milor on my dataset which are integrated data from different organs built by using seurat integration method. When I perform this step I am facing error message. 

> rownames(embryo_design) <- embryo_design$ident
Avis : non-unique values when setting 'row.names': ‘0’, ‘0_immat’, ‘1’, ‘1_immature’, ‘2’, ‘2_immature’, ‘3’, ‘3_immature’, ‘4’, ‘5’, ‘7’Erreur dans `.rowNamesDF<-`(x, value = value) :   les duplications dans 'row.names' ne sont pas autorisées

> rownames(embryo_design) <- embryo_design$orig.ident
Avis : non-unique values when setting 'row.names': ‘lung’, ‘MEDLN’, ‘Thymus_F’Erreur dans `.rowNamesDF<-`(x, value = value) : les duplications dans 'row.names' ne sont pas autorisées

If I try to follow with the testNhoods step it does not run properly :

> da_results <- testNhoods(embryo_milo, design = ~ orig.ident + ident, design.df = embryo_design)
Erreur dans testNhoods(embryo_milo, design = ~orig.ident + ident, design.df = embryo_design) : 
  Design matrix (9998) and nhood counts (3) are not the same dimension

How can I manage those problems?

<img width="570" alt="image" src="https://user-images.githubusercontent.com/101135798/213408146-5cba2449-0cfc-483e-a9a1-5783bf3d0770.png">


My embryo milo object look like this? 

class: Milo 
dim: 2000 9998 
metadata(0):
assays(1): logcounts
rownames(2000): Ccl5 Olfr1369-ps1 ... Mfsd2a Crybb3
rowData names(0):
colnames(9998): Thymus_F_AAACCTGGTAGCGCTC-1 Thymus_F_AAACCTGGTCATACTG-1 ... lung_TTTGTTGGTGAATGAT-1
  lung_TTTGTTGTCCGTCACT-1
colData names(66): orig.ident nCount_RNA ... list.dig.1 ident
reducedDimNames(2): PCA UMAP
mainExpName: integrated
altExpNames(0):
nhoods dimensions(2): 9998 734
nhoodCounts dimensions(2): 734 3
nhoodDistances dimension(1): 734
graph names(1): graph
nhoodIndex names(1): 734
nhoodExpression dimension(2): 1 1
nhoodReducedDim names(0):
nhoodGraph names(0):
nhoodAdjacency dimension(2): 1 1


Many thanks in advance for your help

**Comment by MikeDMorgan** [comment]
Hi @A-legac45 firstly - this is a separate problem, so really should be a new issue opened. The next point, is that the error message tells you exactly what the problem is: 
```Design matrix (9998) and nhood counts (3) are not the same dimension```

You only have 3 experimental samples in your nhood counts matrix and you are trying to use a design matrix with 9998 rows - clearly that is your issue.

**Comment by A-legac45** [comment]
thanks for your answer but the nhood count is made by orig.ident while the nrow is the name of the different genes present in the dataset. I do not get how to make it properly running

**Comment by A-legac45** [comment]
My command are the following from a seurat object V4

embryo_data <- as.SingleCellExperiment(T_MES_L_reg_sub, assay = "integrated")
T_MES_L_reg_sub_milo <- Milo(embryo_data)
T_MES_L_reg_sub_milo <- buildGraph(T_MES_L_reg_sub_milo, k = 30, d = 30, reduced.dim = "PCA")
T_MES_L_reg_sub_milo <- makeNhoods(T_MES_L_reg_sub_milo, prop = 0.1, k = 30, d=30, refined = TRUE, reduced_dims = "PCA")

plotNhoodSizeHist(T_MES_L_reg_sub_milo)
embryo_milo <- countCells(T_MES_L_reg_sub_milo, meta.data = as.data.frame(colData(T_MES_L_reg_sub_milo)), sample="orig.ident")

head(nhoodCounts(embryo_milo))

design <- data.frame(colData(embryo_milo))[,c("orig.ident", "ident")]

## Convert info from integers to factor
design$ident <- as.factor(design$ident)

**Comment by A-legac45** [comment]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/101135798/213415685-f3bcf16b-2d64-44da-b856-ad20d46799d2.png">

**Comment by MikeDMorgan** [comment]
The original issue is about making sure that the rownames of your design matrix match the column names of your nhood count matrix. The code you posted has an nhood count matrix with 3 columns and a design matrix with 9998 rows which is why you get the error:
```da_results <- testNhoods(embryo_milo, design = ~ orig.ident + ident, design.df = embryo_design)
Erreur dans testNhoods(embryo_milo, design = ~orig.ident + ident, design.df = embryo_design) :
Design matrix (9998) and nhood counts (3) are not the same dimension```

Your code is wrong for 2 reasons: 1) you are using the _single-cell_ meta-data, not the _sample_ meta-data and 2) the rownames of the meta-data do not match the names of your samples.

**Comment by A-legac45** [comment]
do you mean that this type of analysis can not be perform on integrated data by seurat?

> T_MES_L_reg_sub
An object of class Seurat 
33053 features across 9998 samples within 2 assays 
Active assay: RNA (31053 features, 0 variable features)
 1 other assay present: integrated
 2 dimensional reductions calculated: pca, umap
<img width="795" alt="image" src="https://user-images.githubusercontent.com/101135798/213418524-2656b92c-52e7-4c07-9b1f-3544a9a058bc.png">

**Comment by MikeDMorgan** [comment]
This has nothing to do with Seurat, this is entirely that the dimensions of your data are wrong. I strongly recommend that you read the `Milo` documentation in detail and read through the workflow/vignettes to understand what is happening at each step. 

In your data, the nhoods count matrix has 3 columns - that means that you only have 3 experimental samples - and implies that you don't have multiple replicates if these are from different tissues, and that you want to identify differential abundance between tissues. You need replicates in your experiment to run Milo.

When you are running `testNhoods` the `design.df` must have the same number of rows as there are columns of your nhood count matrix, in your case that is 3. In your _code_ your input to `design.df` has 9998 rows. 3 != 9998. Simple.

**Comment by A-legac45** [comment]
ok thanks
