### ISSUE TITLE
Query - input data/batch correction/DGE downstream functions

### ISSUE THREAD

**Issue by tomthomas3000** [MarioniLab/miloR#151]
Thank you miloR team for a great package! It has been super helpful especially when studying pertubations in-vivo!

I wanted to confirm a few things about use of milo_gastrulation vignette and the package if thats alright:

1) Just to double-check, should the input count matrix should be raw gene expression data (i.e. not normalised/not log/transformed or scaled etc.)? Particularly as downstream analyses (Section 5.0.1) appear to log-normalise the counts and there are DGE analyses downstream?

2) In the case of batch correction methods like harmony, I presume harmony-corrected PCA embeddings can be substituted instead of the fastMNN your team has used in the runUMAP(dimred = "pca.corrected") step within the "2 Visualize the data"section?

3) Better yet, if we already have harmony-based UMAP co-ordinates pre-computed, I suppose this entire step "2 Visualize the data" and downstream analyses can be performed using those UMAP co-ordinates?

4) Can I confirm that prior to both: i) cases where all the DA neighbourhoods seem to belong to the same region of the graph (as in section 5.0.1) and ii) running buildNhoodGraph (section 5.1) for cases where DA neighbourhoods are found in different areas of the KNN graph, that logNormCounts needs to be performed. The vignette shows it explicitly in section 5.0.1 and hence did not need to be run again for section 5.1.

5) Is the DGE tests within the package, run on the raw counts ?

Thank you ever so much again for a valuable contribution to the community. 

Kind Regards,
Tom

**Comment by MikeDMorgan** [comment]
Hi @tomthomas3000 thanks for your interest in Milo.  

To answer your questions:
>     1. Just to double-check, should the input count matrix should be raw gene expression data (i.e. not normalised/not log/transformed or scaled etc.)? Particularly as downstream analyses (Section 5.0.1) appear to log-normalise the counts and there are DGE analyses downstream?

The vignette using the `MouseGastrulationData` package is purely for illustrative purposes. In reality the input step for Milo is the kNN graph. Choices up until that point are entirely down to the user. Regarding gene expression normalisation (as you note), this is purely for the purposes of visualisation DGE testing. The latter can use either normalised or raw counts, controlled by passing `assay=c("counts", "logcounts")` (delete as necessary).

>     2. In the case of batch correction methods like harmony, I presume harmony-corrected PCA embeddings can be substituted instead of the fastMNN your team has used in the runUMAP(dimred = "pca.corrected") step within the "2 Visualize the data"section?

You can use whichever batch-correct method your prefer. We do however, recommend using a method that returns either a corrected gene expression or reduced dimensional space, as there as some distance calculation steps in the Milo workflow.

>     3. Better yet, if we already have harmony-based UMAP co-ordinates pre-computed, I suppose this entire step "2 Visualize the data" and downstream analyses can be performed using those UMAP co-ordinates?

We only use the UMAP for visualisation. If you already have a set of UMAP co-ordinates then by all means use these. They can be added to the Milo object using the `reducedDim` function. We do not use the UMAP co-ordinates for any down-stream analyses (though they are useful for anchoring the neighbourhood graph visualisation), i.e. don't use them to directly compute the kNN-graph (note: you can add your own kNN-graph that matches your UMAP if you wish).
 
>     4. Can I confirm that prior to both: i) cases where all the DA neighbourhoods seem to belong to the same region of the graph (as in section 5.0.1) and ii) running buildNhoodGraph (section 5.1) for cases where DA neighbourhoods are found in different areas of the KNN graph, that logNormCounts needs to be performed. The vignette shows it explicitly in section 5.0.1 and hence did not need to be run again for section 5.1.

The `logNormCounts` is purely for the gene expression normalisation, and subsequent _post hoc_ DGE testing. It is not a requirement _per se_ for the differential abundance testing framework.

>     5. Is the DGE tests within the package, run on the raw counts ?

As stated above, DGE testing can use either the raw or normalised counts controlled by passing either `assay="logcounts"` (normalised) or `assay="counts"` (raw counts) to the respective DGE testing functions.

> 
> Thank you ever so much again for a valuable contribution to the community.
> 
> Kind Regards,
> Tom

Your welcome Tom - I hope this helps to answer your questions.
