### ISSUE TITLE
Work with multiple groups 

### ISSUE THREAD

**Issue by YubinXie** [MarioniLab/miloR#158]
Hi MILO team,

Thanks for the great works. I am currently working with data with multiple groups, and I want to test abundance in my dataset with n=7 groups. I tried MILO and the code works. But I looked into the code and it seems it is only comparing my last group to the first group. Is this possible for MILO to support multiple group abundance test and visualization? In a context like one vs the rest for example.Thanks!

**Comment by MikeDMorgan** [comment]
Hi @YubinXie The way that the actual differential abundance testing is performed depends on the experimental variable being used. For instance, if your variable is numeric and encoded 1, 2, 3, ... then R will naturally see this as a continuous quantitative variable and treat it as such in the GLM. Consequently the comparison will then be the average _across_ groups, assuming a uniform difference between groups.

If you wish to perform a 1 vs. all test, you can encode this using a dummy variable, where you set observations with the group of interest to 1, and all others to 0. Alternative approaches, such as comparing groups 1 vs 3+5 can also be encoded by using the `contrasts` options in `testNhoods`.

**Comment by LASeeker** [comment]
Hello @MikeDMorgan, 
I am still wondering about this, too. I would like to know how much the neighbourhoods in my object differ with tissue region ("Tissue") which is a factor with three levels ("BA4", "CB", "CSC"). When I simply fit "Tissue" 

da_results <- testNhoods(milo_obj, design = ~ Tissue, design.df = milo_design)

the output looks like it is taking the alphabetically last level "CSC" and compares it to the first "BA4" which is similar to what @YubinXie described above. I looked up your answer above and found "model.contrasts" as additional argument for testNhoods(), but am not clear about the syntax. The help page says it is "A string vector that defines the contrasts used to perform DA testing." But when I try the following for example:

da_results <- testNhoods(milo_obj, design = ~ Tissue, design.df = milo_design,
                         model.contrasts = c("CB", "BA4"))
                         
I get an error: "Error in eval(ej, envir = levelsenv) : object 'CB' not found"

I am sure this is me misunderstanding how the syntax is supposed to look like but I would be very grateful, if you could show using an example how I specify contrast levels. You also said I could do one level vs. two others. How would that look like? 

Thank you!

**Comment by MikeDMorgan** [comment]
Hi @LASeeker Thanks for your interest in Milo. Contrasts are a bit tricky (there is a long series of threads on Biostars on this topic regarding their use in `limma` and `edgeR`). We use the same syntax in Milo, so the the contrasts are exactly that, they are comparisons between two (groups) of variables. 

In your example comparing 'CB' vs 'BA4' the correct input would be `model.contrasts = c("TissueCB - TissueBA4")`, assuming that you want the 'BA4' level to be the reference (think of this in terms of computing a fold change on a log scale, i.e. log(a/b) = log(a) - log(b), so b would be our reference here.

The general syntax for contrasts is `variableNameLevel`, all as one string.

Given the confusion over this issue - we clearly need to improve the documentation to clarify how they are used.

**Comment by LASeeker** [comment]
Hi @MikeDMorgan, 

Thank you very much! This is really helpful indeed! When you are updating the documentation (which would- I am sure- be very much appreciated regarding this specific issue) it may also be helpful to add how to compare one factor level to two or more others. I don't need this right now, but I could imagine that would be the next question. 

Unfortunately, this is still not working for me:

da_results <- testNhoods(milo_obj, design = ~ Tissue, design.df = milo_design,
                         model.contrasts = c("TissueCB - TissueBA4"))

Error in eval(ej, envir = levelsenv) : object 'TissueBA4' not found

I checked both the  milo object in the design matrix and Tissue with the level BA4 is definitely present in both although there is indeed no object called "TissueBA4".

> head(colData(milo_obj)$Tissue)
[1] "BA4" "BA4" "BA4" "BA4" "BA4" "BA4"

> head(milo_design)
               uniq_id Tissue gender AgeGroup   
HCA_10  HCA_10    BA4      M      Old 
HCA_01  HCA_01    BA4      F    Young 
HCA_44  HCA_44    BA4      F      Old 
HCA_55  HCA_55    BA4      M    Young 
HCA_03  HCA_03    BA4      F    Young 
HCA_04  HCA_04    BA4      M    Young 

I'll have a look on Biostars as I realise this may go beyond the Milo library and I may have to read up on contrasts in limma and edgeR. But if you can think of a solution, I'd be happy to hear from you. 

Thank you!

**Comment by LASeeker** [comment]
Sorry, header in design matrix above are moved to the left. First "column" are the row names.

**Comment by MikeDMorgan** [comment]
Can I just get you to check if it runs without if you use `design = gender + Tissue`?

**Comment by LASeeker** [comment]
I checked, but it remains the same problem:

da_results <- testNhoods(milo_obj, design = ~ gender + Tissue, design.df = milo_design,
                         model.contrasts = c("TissueCB - TissueBA4"))
                         
Error in eval(ej, envir = levelsenv) : object 'TissueBA4' not found

**Comment by MikeDMorgan** [comment]
Ok, and if you pass `model.contrast=c("CB _ BA4")`? (sorry, I'm just trying to debug this).

**Comment by LASeeker** [comment]
I am grateful you are trying to debug this!

da_results <- testNhoods(milo_obj, design = ~ Tissue, design.df = milo_design,
                         model.contrasts = c("CB - BA4"))
                         
Error in eval(ej, envir = levelsenv) : object 'CB' not found

**Comment by MikeDMorgan** [comment]
OK, leave this with me - I think I know what the issue is, but need to double-check.

**Comment by LASeeker** [comment]
Wonderful! Thank you for taking this seriously and being so helpful!

**Comment by MikeDMorgan** [comment]
Hi @LASeeker Could you run this using `design = ~ 0 + Tissue` and `model.contrasts=c("TissueCB - TissueBA4")`?

**Comment by LASeeker** [comment]
Hi @MikeDMorgan, 

Fantastic, this worked! I am thrilled. Thank you very much for your help! I noticed though that CB is now the reference level which is not a problem at all, but may be useful to know. 

I also think it does not work when fitting additional fixed effects in the same model. Don't know if you'd expect that. But for me and what I want to do this works really nicely now!

Thank you so much for all the time you spent on figuring this out today!

**Comment by MikeDMorgan** [comment]
Hi @LASeeker  - yes, I need to figure out how to tweak it to also include covariates, I'm glad this is working though (sorry about getting the test/reference the wrong way round).
