### ISSUE TITLE
Small typo in the Readme

### ISSUE THREAD

**Issue by Martin-Fahrenberger** [MarioniLab/miloR#161]
Hi miloR Team,

Thanks for your work on milo, looks promising!

I just quickly wanted to point out a typo in the Readme file.
In the example workflow you call "milo.obj <- calcNhoodDistances(milo.obj, d=30)"
But as far as I can tell "calcNhoodDistances" should be "calcNhoodDistance".

Just wanted to make sure no one gets confused trying the example :)

**Comment by MikeDMorgan** [comment]
Thanks for the catch!
