### ISSUE TITLE
hilled p-value histogram

### ISSUE THREAD

**Issue by lindsaynhayes** [MarioniLab/miloR#162]
I have 120K cells from 18 samples across 4 groups. I processed this with Seurat using sctransform normalization and reciprocal PCA integration. For the Milo analysis I converted to a SCE and copied the PCA and UMAP over so the neighborhoods were in the already defined seurat_clusters. I wrote out my contrasts according to issue #101 (awesome thread). I have 0-few DA neighborhoods so I started digging since the fold changes were reasonable. **I found the p-value histograms were right skewed/hilled instead of a uniform distribution of p-values. This makes me concerned that something isn't right. Do you have suggestions for troubleshooting this or where else to look for problems?** The mean-var plot was weird on the Seurat Object so when I converted it to a SCE I redid `logNormCounts(sce)` and refit the `modelGeneVar` and then the mean-var plot looked normal, but the Milo p-val histogram still looked the same. 

```
MILO <- as.SingleCellExperiment(SeuratObject)
reducedDim(MILO, "PCA", withDimnames=TRUE) <- Filt[['pca']]@cell.embeddings
reducedDim(MILO, "UMAP", withDimnames=TRUE) <- Filt[['umap']]@cell.embeddings
MILO_obj <- Milo(MILO)
MILO_obj <- buildGraph(MILO_obj, k = 40, d = 30, reduced.dim = "PCA")
MILO_obj <- makeNhoods(MILO_obj, prop = 0.15, k = 40, d=30, refined = TRUE, reduced_dims = "PCA")
plotNhoodSizeHist(MILO_obj)  ## peak around 100 (5 x 18 = 90)
MILO_obj <- countCells(MILO_obj, meta.data = data.frame(colData(MILO_obj)), sample="sample")
MILO_obj <- calcNhoodDistance(MILO_obj, d=30, reduced.dim = "PCA")
MILO_obj <- buildNhoodGraph(MILO_obj)
MILO_design <- data.frame(colData(MILO_obj))[,c("sample", "group")]
MILO_design$group <- as.factor(MILO_design$group)
MILO_design$sample <- as.factor(MILO_design$sample)

MILO_design <- distinct(MILO_design)
rownames(MILO_design) <- MILO_design$sample
str(MILO_design)
design <- model.matrix(~ 0 + MILO_design$group)
rownames(design) <- MILO_design$sample
colnames(design)
colnames(design) <- c("CON, "CON.TRT", "EXP", "EXP.TRT")
MCvCC <- makeContrasts("EXP - CON", levels= design)
MPvCC <- makeContrasts("EXP.TRT- CON", levels= design)
CPvCC <- makeContrasts("CON.TRT - CON", levels= design)

da_results_MCvCC <- testNhoods(MILO_obj, design = ~ 0 + group, design.df = MILO_design, model.contrasts = "groupEXP - groupCON")
da_results_MCvCC %>% arrange(PValue) %>% head()
plotNhoodGraphDA(MILO_obj, da_results_MCvCC, layout="UMAP", alpha=1, res_column = "logFC")
ggplot(da_results_MCvCC, aes(PValue)) + geom_histogram(bins=50)

sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
miloR_0.99.18 
```

![Milo_MCvCC_pval](https://user-images.githubusercontent.com/23195950/124820350-6249cb80-df3b-11eb-8903-e47647825a5c.jpg)

**Comment by MikeDMorgan** [comment]
Hi @lindsaynhayes Intuitively I would say this indicates that the test is overly conservative. Can I also ask what the MAplot looks like, i.e. are the log fold change values 0-centred, and does it look like there is any censoring of log fold-changes, or does it look overly compressed in the y-axis?

If you subset your analysis to just the samples from the "CON" and "EXP" levels of `group`, do you still get the same distribution of p-values?

I also wonder if there might be some other factor/covariate that relates these samples, such as a processing batch, or something similar?

**Comment by MikeDMorgan** [comment]
Hi @lindsaynhayes Did you resolving the p-value hilling issue? I have personally seen this as well where a confounding variable was not accounted for in the model. Including the confounder resolved the issue for me.

**Comment by lindsaynhayes** [comment]
Yes, I had a cluster of cells that had higher mitochondrial reads and lower counts. When I filtered out these cells the p-value distribution looked more even or left tailed as expected.
