### ISSUE TITLE
Extract the matrix of cells and their neighbourhoods

### ISSUE THREAD

**Issue by KASHISH72** [MarioniLab/miloR#163]
Hi,
Great tool
Can you suggest a way i can extract a matrix for the cells and their neighborhoods from the milo.
It would be really helpful for me to get the matrix.
And One more thing when I am using the function nhoods(traj_milo), why does the column header represent in that.

**Comment by MikeDMorgan** [comment]
Hi @KASHISH72 The `nhoods` function returns the cell X neighbourhood indicator matrix, therefore the rows are the indices of the cells in your data, and the columns are the neighbourhood that they are assigned to.

**Comment by KASHISH72** [comment]
Thanks,
Can you tell me, What does the column header number means ? 
And can we also extract where does the neighborhoods are present as their coordinates?

**Comment by MikeDMorgan** [comment]
Hi @KASHISH72 As I stated above, the columns correspond to the neighbourhoods (these are just numbered). The neighbourhoods are defined by the index cell, which can be retrieved using the `nhoodIndices()` function.

I would also strongly recommend working through the package vignettes and documentation, as all of the answers to your questions can be found there.

**Comment by KASHISH72** [comment]
Hello Mike,

Thanks for your suggestion, it worked. I have one more question regarding the number of neighborhoods. Can you tell me the way I can reduce the number of neighborhoods ? For now i have around 300 neighborhoods and I would like to have less around 40-50 groupings of the neighborhoods. Which options would be good to reduce the number of nhoods?

**Comment by MikeDMorgan** [comment]
Hi @KASHISH72 For the purposes of DA testing, we would recommend you have a minimum neighbourhood size of 5xS, where S is the total number of biological samples. To achieve this you can inspect the histogram of plot sizes, which can be visualized using the `plotNhoodSizeHist()` function. To increase the neighbourhood size you can increase `k` in `buildGraph` and `makeNhoods` (note these should be the same value), and _vice versa_ to decrease the neighbourhood size. Alternatively, you can alter the initial sampling proportion `p` in the `makeNhoods()` function.

I would stress that the idea behind Milo is to generate a near-representative set of neighbourhoods, so reducing the number of neighbourhoods would be achieved by by making them less representative, i.e. increase `k` in the graph building step. This will result in a much lower resolution of cell states, so I would question why you explicitly want to reduce the number of neighbourhoods?

**Comment by MikeDMorgan** [comment]
Closing for now - please re-open if you issue has not been resolved.

**Comment by friedue** [comment]
> Hi @KASHISH72 As I stated above, the columns correspond to the neighbourhoods (these are just numbered). The neighbourhoods are defined by the index cell, which can be retrieved using the `nhoodIndices()` function.

Just a comment for future users: the function name is actually `nhoodIndex()`.

It *is* a little confusing that the colnames of the `nhoods()` output (where you use the index cells) aren't equivalent with the Nhood entry in the `testNhoods()` output (where they seem to be simply numbered from 1:n). Not a big issue, of course, but a minor roadblock for users trying to familiarize themselves with the objects

**Comment by MikeDMorgan** [comment]
Hi @friedue Thanks for the feedback - this is something that we can incorporate as we update `Milo`.
