### ISSUE TITLE
Error in testNhoods

### ISSUE THREAD

**Issue by WonderfulJob** [MarioniLab/miloR#165]
Hi miloR Team, 
I wander konw Why i can't perform function testNhoods( )  and how to set **samples** and **condition** when create a miloR object from Seurat object. 
Even when i used example dataset, there's still the same error here:
![image](https://user-images.githubusercontent.com/48800451/128628330-c38b576e-f0d4-4e1a-8119-4565f2b11b8d.png)
Looking for your answer!
: (

**Comment by emdann** [comment]
Hello, 
This error appears if `rownames(milo.design) != colnames(nhoodCounts(milo.obj))`. Could you check if you get the same if you set `rownames(milo.design) <- milo.design[,"Sample"]`? 
And just to be sure, are you using the latest version of the package installed by `BiocManager::install("miloR")`?

**Comment by WonderfulJob** [comment]
I set **rownames(milo.design) <- milo.design[,"Sample"] but it didn't  work !**
![image](https://user-images.githubusercontent.com/48800451/129169284-062bf7c8-58ad-4c99-aef6-e70e2692953c.png)

I realized it may because of the wrong order, so I set **milo.design <- milo.design[colnames(nhoodCounts(milo.obj)),]** and it work!
![image](https://user-images.githubusercontent.com/48800451/129170978-8055951c-5f83-4d5c-8ded-7aa5992f2141.png)

**Comment by emdann** [comment]
Good to hear this was solved! Just FYI if the ordering is different `testNhoods` just throws a warning message and reorders internally, so it should still run the test properly (https://github.com/MarioniLab/miloR/blob/8fc49974f2221fe80628973427d60400756fed37/R/testNhoods.R#L177-L179). 

Closing this now, feel free to reopen if issues persist.
