### ISSUE TITLE
Errors when running milo_in_python.ipynb

### ISSUE THREAD

**Issue by KongMingxi** [MarioniLab/miloR#179]
Hi authors,

Many thanks for your excellent work and contributions! When I ran the example in the milo_in_python.ipynb, I got this error:

> RRuntimeError: Error in validObject(.Object) : 
  invalid class "dgCMatrix" object: 1: invalid object for slot "i" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class "dgCMatrix" object: 2: invalid object for slot "p" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class "dgCMatrix" object: 3: invalid object for slot "Dim" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class "dgCMatrix" object: 4: invalid object for slot "x" in class "dgCMatrix": got class "array", should be or extend class "numeric"

I was wondering how I could figure it out?

Best,
Mingxi

**Comment by emdann** [comment]
I'm having a hard time reproducing this error. Could you share the output of 
```
sc.logging.sinfo()
``` 
and
```
%%R
sessionInfo()
```
?
