### ISSUE TITLE
miloR for cytometry data

### ISSUE THREAD

**Issue by jwiarda** [MarioniLab/miloR#187]
For analyzing differential abundance of mass cytometry or flow cytometry data, would it be recommended to still use cydar and calculate cell spheres, or would use of cell neighborhoods calculated using miloR present as an improved option?

**Comment by MikeDMorgan** [comment]
Hi @jwiarda  We haven't done a side-by-side comparison on Mass or flow cytometry data, so I can't give you an evidence-based answer unfortunately. If you have processed your data into a reduced dimension space, then you could compare and contrast the results from Cydar and Milo _ad hoc_.
