### ISSUE TITLE
Would it be possible to extend models with a random effect?

### ISSUE THREAD

**Issue by LASeeker** [MarioniLab/miloR#188]
Hello, 

We have been testing Milo on different datasets and a variety of species and overall we are very happy with the results. As most of us are aware, humans are hugely variable and therefore I am wondering if it would be possible to adapt the model framework so that it can consider random effects as well to account for donor variation in a setting where there are repeat samples for each donor? 

Thank you!

**Comment by MikeDMorgan** [comment]
Hi @LASeeker This is indeed on our development roadmpa, however, developing a mixed effect model in this context is very non-trivial unfortunately. If computational time is not a bottleneck for you then you could fit individual GLMMs for each neighbourhood counts vector using something like `glmmTMB`. Note that I haven't tested this, but it would at least allow you to account for repeated measurements.

**Comment by LASeeker** [comment]
Thank you @MikeDMorgan for your prompt response! Good to hear that you are thinking about this already. I believe it would be very helpful for a lot of people working with human data. I appreciate that this is non-trivial! In the meantime thank you for your advice with the glmmTMB. I'll have a look at those.
