### ISSUE TITLE
findNhoodGroupMarkers adjusted P values have the same order for all NhoodGroup

### ISSUE THREAD

**Issue by Zepeng-Mu** [MarioniLab/miloR#191]
Hi, I'm running `findNhoodGroupMarkers` but I found that the order of adjusted P-value are actually the same for different NhoodGroups. I'm not sure where I did wrong.

```r
dge_smp <- findNhoodGroupMarkers(
  miloCmb,
  daRes,
  assay = "logcounts",
  gene.offset = T,
  subset.row = hvgs,
  aggregate.samples = T,
  sample_col = "indiv"
)
```

```r
> identical(dge_smp$GeneID[order(dge_smp$adj.P.Val_1)], dge_smp$GeneID[order(dge_smp$adj.P.Val_2)])
[1] TRUE
```

I'm wondering whether there is any ways I can test what went wrong in my analysis.
Thanks so much!

**Comment by MikeDMorgan** [comment]
Without any other info it's hard to say anything useful. For instance, are these nhoodgroups well separated? It might be that they genuinely share the same markers - again, without any info I can't tell if this is incorrect or not. 

I agree that these being perfectly the same is weird - what is the distribution of these FDRs, and are they _identical_?

**Comment by Zepeng-Mu** [comment]
Hello, I ran the `findNhoodGroupMarkers` code line by line, and the results look like this:

```sh
> head(marker.list[[1]])
                 logFC_1  adj.P.Val_1
RP11-677O4.6  0.04938650 0.0004220246
DEFB121       0.06977120 0.0004220246
CDC42P2       0.08553940 0.0007481375
RP11-744K17.3 0.11651560 0.0007481375
RP11-19P22.7  0.14688104 0.0011337778
AMER2         0.05541815 0.0023470665
> head(marker.list[[2]])
               logFC_2  adj.P.Val_2
MYLK4        0.2823351 3.216016e-05
LIPF         0.2086906 3.455098e-05
RP5-947P14.2 0.2182468 3.455098e-05
KCTD16       0.3330047 3.620338e-05
LINGO1       0.3482715 3.620338e-05
RP11-463C8.5 0.3364033 3.899865e-05
> head(marker.list[[3]])
                logFC_3  adj.P.Val_3
RP11-638L3.2 0.16636466 6.720229e-11
RP11-700N1.1 0.09329541 1.899045e-10
CTC-394G3.1  0.18395549 1.899045e-10
LINC00210    0.15563010 1.899045e-10
BRINP3       0.34101413 3.171553e-10
RP1-104O17.3 0.13791818 3.414622e-10
```

However, the output from the line is very strange:
https://github.com/MarioniLab/miloR/blob/abeed5abb64b227ef2f0c95a9c4931b043c64a3f/R/findNhoodGroupMarkers.R#L235
```r
> Reduce(x=marker.list, f=function(x, y) all(rownames(x) == rownames(y)))
[1] TRUE
```

The line names are clearly not the same. Why would this be `TRUE`?
Indeed I didn't get the warning "Rownames of DGE results are reordered" when I was running the function.

**Comment by MikeDMorgan** [comment]
I agree this is strange. Can you double-check what `all(rownames(marker.list[[1]]) ==rownames(marker.list[[2]]))` actually returns? i.e. are these all the same length with no `NA` values?

**Comment by Zepeng-Mu** [comment]
It seems that it always returns `T` when marker.list has three or more elements. I think `Reduce` is causing problem here?

**Comment by Zepeng-Mu** [comment]
I think this should work `Reduce(x=marker.list, f=function(x, y) identical(rownames(x), rownames(y)))`

**Comment by MikeDMorgan** [comment]
Hi @Zepeng-Mu - could you try re-installing from the devel branch and see if this problem persists: `devtools::install_github("MarioniLab/miloR", ref="devel")`

**Comment by Zepeng-Mu** [comment]
Hi, I installed the `devel` branch but the results are still the same as before. Every group has adj.P order from small to big and the order are all the same.

**Comment by MikeDMorgan** [comment]
Hi @Zepeng-Mu I've pushed a simplification which also revealed there was a more extensive bug - thank you for raising this issue as it wasn't covered in our unit tests.  The latest changes are now on the `devel` branch.
