### ISSUE TITLE
Extract barcodes from all cells that belong to a scRNA-seq dataset neighborhood

### ISSUE THREAD

**Issue by tkapello** [MarioniLab/miloR#195]
Hello,

More of a question rather than an issue. I was reading on `MiloR `and wanted to use this tool to identify neighborhoods in my scRNA-seq dataset that correlate in abundance with a treament of interest. What I want to do in downstream analysis is to extract the barcodes of cells that belong to a neighborhood and perform a statistical comparison of gene expression with the rest cells in the same cluster. I understood that this is not possible since `MiloR` uses index cells to represent the neighborhoods, but the barcode identities of all cells that belong tothis neighborhood is not accessible. Am I right or is this information stored in the object, as well?

Thanks in advance!

**Comment by MikeDMorgan** [comment]
Hi @tkapello  I have just replied to your question on the Bioc forum - it is generally good practise to only post a question on one forum and allow the relevant parties an opportunity to respond first.
