### ISSUE TITLE
calcNhoodExpression does not return correct nhood #s/ids 

### ISSUE THREAD

**Issue by rdchow** [MarioniLab/miloR#197]
Hello,

I am trying to use calcNhoodExpression to get the average expression of select genes in each neighborhood, and to then visualize these expression data grouped by the miloR differential abundance results (in essence, mimicking the processing steps of plotNhoodExpressionGroups).

However, while the resulting data frame of calcNhoodExpression has the correct # of dimensions (ncol = # of neighborhoods), the column names of the resulting data frame are not named the same way as the Nhood names produced by testNhoods.

Looking into the code for plotNhoodExpressionGroups, I'm _pretty_ sure that the Nhood names as produced by testNhoods are made by numbering each column sequentially starting from 1, since I see the colnames there are set to seq_len(ncol(nhoods(x))). Still, I think this would be a useful edit to the code for calcNhoodExpression so that the column names will by default correspond to the Nhood names from testNhoods.

Thanks.

**Comment by MikeDMorgan** [comment]
The column names refer to the index cells in `nhoodIndex` slot. I will update the documentation to better describe this. Note that the _ordering_ of nhoods is identical throughout though.
