### ISSUE TITLE
Milo results in cell-cell communication

### ISSUE THREAD

**Issue by tkapello** [MarioniLab/miloR#199]
Hi,

   I want to run some a cell-cell communication tool on the outcome of a Milo neighborhood abundance analysis. My rationale is that if there exist neighborhoods in a cluster that are differentially abundant between a treatment and a control sample, then one would be interested to find out how these cell groups interact with each other in the two conditions. My only concern is that Milo may generate too many neighborhoods from every defined cell cluster which would make such an analysis unrealistic and computationally expensive. I thought I could tweak the neighborhood size parameter to return bigger (and fewer) ones or to perform the cell-cell communication analysis only on the neighborhoods with highest and lowest logfc between the conditions. Any thoughts/suggestions would be welcome here.

**Comment by MikeDMorgan** [comment]
My gut instinct would be that nhoods aren't a great input to most cell-communication tools as they will fail to account for the overlap between neighbourhoods. For now I'd stick with using the discrete clustering, or a more fine-grained sub-clustering. I think a bespoke tool would be needed to work directly with neighbourhoods - this is something I've been thinking about, but don't have the manpower for right now (though I'm hoping this will change in the next 12 months or so).
