### ISSUE TITLE
Cannot open R tutorials

### ISSUE THREAD

**Issue by Eddylyf** [MarioniLab/miloR#201]
Hi,
Very nice and useful software! But it seems that R tutorial links not working anymore:
1. Basic Milo example on simulated dataset.
2. Milo example on mouse gastrulation dataset: this includes a demo for downstream analysis functions.
Could you please fix this issue?
Thanks so much!
Best.

**Comment by emdann** [comment]
Hi @Eddylyf, thanks for flagging this but the links in the github README look fine on our side. Do you have a version of the package installed from github some time ago? Please be aware that the same tutorials are also available via Bioconductor https://bioconductor.org/packages/release/bioc/html/miloR.html

**Comment by Eddylyf** [comment]
Hi @emdann, thanks for your suggestions, the Bioconductor tutorials link are available for me! Indeed I had a version of the package installed from github. Thanks again!
