### ISSUE TITLE
Comments on contrast vignette

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloR#202]
1. The vignette title might be a bit obscure for someone that doesn't know what constrasts are. How about "Specifying comparisons for differential abundance testing using contrasts"
2. Line 64: add "We now build the KNN graph and define neighbourhoods to quantify cell abundance."
3. Line 76: rephrase 
> The essence behind using contrasts is to define concretely which groups will be compared to which.

To 
> Contrasts are a way to define explicitly which groups will be compared to which.
4. Line 94: I'd write in the comment `# the syntax is <VariableName><ConditionLevel> - <VariableName><ControlLevel> `
5. Line 96: add a line on why here we use `design = ~ 0 + Age` rather than `design = ~ Age`
6. Line 123: in this chunk you use the edgeR code instead of passing `mod.contrasts[,1]` to `testNhoods` because `testNhoods` just takes strings in input, right? But why do you need to show all this instead of running `testNhoods` with `contrasts = contrast.all[1]`? If there is a specific reason that I am missing or even if it's just to demonstrate the inner workings, I would specify above this chunk.
7. Line 179: add link to the mentioned edgeR documentation, maybe specific page on contrasts? 
8. Section titles: maybe change "Milo analysis" to "Define cell neighbourhoods" and "Differential abundance testing" to "Differential abundance testing with contrasts" 

All runs smoothly installing from `devel` branch! Only problem was the 4.1 requirement, not sure if that will annoy other users

**Comment by MikeDMorgan** [comment]
Fab, thanks Emma. The R version dependency is from Bioconductor, so not much can be done there. Arguably I think users should really switch to 4.1 anyway as Bioc is the preferred installation route.
