### ISSUE TITLE
countCells throws error if samples is a factor and some samples have 0 cells

### ISSUE THREAD

**Issue by amissarova** [MarioniLab/miloR#205]
When running `countCells` on sce, where samples are factors and some samples have 0  cells, the error occurs (works ok if you move samples from factors to characters): 

```
class(sce_milo$sample)
[1] "factor"
> table(sce_milo$sample)

Batch1_Group1 Batch1_Group2 Batch2_Group1 Batch2_Group2 
         5041          4959          4906          5094 
Batch3_Group1 Batch3_Group2 Batch4_Group1 Batch4_Group2 
         4984          5016             0             0 
Batch5_Group1 Batch5_Group2 
            0             0 
> sce_milo <- countCells(sce_milo, meta.data = as.data.frame(colData(sce_milo)), samples="sample")
Checking meta.data validity
Error in replCmat4(x, i1 = if (iMi) 0:(di[1] - 1L) else .ind.prep2(i,  : 
  too many replacement values
 ```

**Comment by MikeDMorgan** [comment]
Hi Alsu, I would question why you would ever have samples stored as a factor - there is no logical ordering of sample IDs so these should always be stored as characters.

**Comment by amissarova** [comment]
Don't you guys have it in the code - the assumption that samples can be stored as factors - so thought you might want to account for this?

**Comment by amissarova** [comment]
P.S. I had them stored as factors cause of downstream plotting I have been doing (in some cases having variables stored as factors makes things easier for `ggplot` )

**Comment by MikeDMorgan** [comment]
There's variables stored as factors, which is fine - but the sample ID isn't a variable, and it has no ordinality, so in the context of setting up the nhoods counts matrix for DA testing it doesn't make sense.
