### ISSUE TITLE
Agile way to "flip" Null Hypothesis

### ISSUE THREAD

**Issue by castaway1990** [MarioniLab/miloR#206]
Hi everyone, thanks a lot for making this tool available to the community, it is a real gamechanger for some of my SC dataset analyses. Maybe mine is a naive question, but I was wondering if there is a way to quickly flip the null hypothesis to assess the invariance between neighbors occupancy among conditions. I Saw that the default null.mean = 0, I'm not sure if setting it to 1 would do the trick.

Thanks.
Davide

**Comment by MikeDMorgan** [comment]
Hi @castaway1990 We don't have functions with an argument of `null.mean`. Do you mean `min.mean` in `testNhoods`? If so, the this is used for filtering out nhoods with low overall counts. We don't currently have any implementation for testing equivalence of nhood counts over conditions. If I recall there is way to do this within the edgeR framework , but it's rather clunky: https://support.bioconductor.org/p/66283/

**Comment by castaway1990** [comment]
You are right, it is  in the function plotNhoodMA() , so only for plotting purposes probably... I will try the solution you pointed out thanks a lot!
