### ISSUE TITLE
Equal cell numbers between conditions?

### ISSUE THREAD

**Issue by asgerjakobsen** [MarioniLab/miloR#208]
Hi, thank you for developing this great tool - I have found it really useful for my analysis. 

I have a question about the differential abundance testing. I am comparing two conditions where there are significantly more cells in one condition than the other (about twice as many in the control (WT) condition versus the test (mutant) condition). I am interested in knowing whether there is a relative increase in cells in particular neighbourhoods in the test condition, compared to controls (i.e. are mutant cells distributed evenly or are there cell states with a relative increase/decrease in abundance, compared to what is seen in controls?).

I have tried running Milo with all cells in the dataset and do detect neighbourhoods with differential abundance, but I am unsure how to interpret the log fold change in this case. Is it calculated from the ratio of test vs control cells in a neighbourhood, or does it somehow take into account the difference in total cell number by normalising? Would it be better to downsample so that I have equal numbers of cells between conditions for testing?

Thanks!
Asger

**Comment by MikeDMorgan** [comment]
Hi @asgerjakobsen Milo does account for differences in the numbers of cells across samples by normalizing in the GLM using trimmed mean of M-values (TMM): https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-3-r25

Depending on how much these differences are confounded with your variable of interest will affect the quality of the normalisation. If there are global differences in the numbers of cells in and across nhoods, then this will be visible as an off-horizontal distribution in an MA plot. You can plot the results of your analysis using `plotNhoodMA()`, you should expect to see the data points distributed around 0 on the vertical axis. If these are drastically diagonal (up or down) then this indicates there is a very strong confounding between the numbers of cells and your experimental conditions, in which case downsampling would be the solution to this problem.

**Comment by asgerjakobsen** [comment]
Thank you for such a quick response!

Yes, that makes sense now. I should have mentioned that I am doing a paired analysis, so from each sample I have both WT and Mut. I have attached an image of my design matrix.  So for testing, my formula is: `design = ~ Sample + clone`.
<img width="578" alt="Screenshot 2022-02-23 at 10 48 54" src="https://user-images.githubusercontent.com/44162825/155304898-7a2bd3d3-3023-4a2d-9b6d-b78e36879177.png">

Here is an image of the MA plot which looks reasonable ok to me:
![image](https://user-images.githubusercontent.com/44162825/155305858-5a020f0c-cd83-4228-af3e-e8e9a9c75927.png)

Do you think I can go ahead without downsampling?

**Comment by MikeDMorgan** [comment]
Hi @asgerjakobsen That MA plot looks fine - I think you're good to go ahead.

**Comment by asgerjakobsen** [comment]
Thank you for your help!

**Comment by alitinet** [comment]
Hi @MikeDMorgan,

I had the same situation in my analysis and as you suggested looked at MA plots for neighborhoods, the first one is what I get when running on unbalanced classes (5k vs 15k cells in each of the conditions) and the second is when I downsampled the second condition to 5k cell too. MA plots don't look that great to me, do you think it's ok to run MILO here or not? And maybe you can also help me interpret these MA plots, e.g. what do these straight lines indicate? Thanks!
![Screenshot 2022-05-27 at 13 41 04](https://user-images.githubusercontent.com/20745228/170696189-f2a801f2-79c5-468e-8c85-1bbccd5849c4.png)
![Screenshot 2022-05-27 at 13 57 31](https://user-images.githubusercontent.com/20745228/170696203-772e991a-84ec-4abf-a0e6-ec4e83827555.png)

**Comment by MikeDMorgan** [comment]
Hi @alitinet These straight lines usually occur when you have nhoods with mostly 0's in them - we _strongly_ recommend inspecting the histogram of nhood counts and make sure that the minumum nhood size is ~N X S, where N is between 5+ and S is the total number of experimental samples.

How many samples do you have in your experiment - this looks suspiciously like you are under-powered.
