### ISSUE TITLE
plotNhoodGraphDA issue

### ISSUE THREAD

**Issue by MarniTorkel** [MarioniLab/miloR#209]
Hi, 

I have an issue with the above plot, the node has no color and the logFC value is 0. Could you please let me know how to extract the color? Thanks.
![Screenshot 2022-03-10 154330](https://user-images.githubusercontent.com/5178671/157591199-412f27ab-94f0-4d7a-99cd-641992e158a2.jpg)

**Comment by MikeDMorgan** [comment]
Hi @MarniTorkel If there are no DA nhoods below your threshold then it will not colour them. To override this set `alpha=1.0`.

**Comment by MarniTorkel** [comment]
Thanks Mike.

Kind Regards,
Marni
