### ISSUE TITLE
About probability P(C1) for simulation data

### ISSUE THREAD

**Issue by mugpeng** [MarioniLab/miloR#212]
Hi,

I recently read your work and also interested about the works related with perturbation. And I was trying to mimic your procedures for creating simulation data and ground truth.

And I was puzzled about some steps.

As mentioned in your paper:
> we simulated single-cell data representing different trajectory geometries (one-dimensional trajectory and branching trajectory) using the R package dyntoy15 as well as discrete clusters. For benchmarking on the KNN graph from real data, we downloaded the raw count matrix and the batch-corrected principal component analysis (PCA) matrix for the mouse gastrulation atlas4 via the R package MouseGastrulationData42.

So in this step, you don't create experimental conditions (C1 and C2) right?

And after that, you process the data to define a ground truth by generating for each cell xi a probability P(C1) of belonging to condition C1. 

However, I didn't find a script describing this step, albeit in the tutorial:
https://rawcdn.githack.com/MarioniLab/miloR/3646391023f600bae00efd9d940b888503d7a536/docs/articles/milo_demo.html
(the simulation data object also in package miloR)

The `sim_trajectory` has been labeled with condition. And there is nothing in [sim_trajectory](https://github.com/MarioniLab/miloR/blob/master/R/sim_trajectory.R)

Hence, I don't know how to repeat your simulations by creating the ground truth about condition labels.

Thanks.

**Comment by emdann** [comment]
Hi @mugpeng 
Thank you for your interest in our work! The description of the condition probability to simulate labels is in the section "Generation of condition probability" of the Methods. The scripts to reproduce the benchmarking analysis are not part of the R package, but in our ms [reproducibility repository](https://github.com/MarioniLab/milo_analysis_2020/tree/main/benchmark).

Specifically, you can find the utility functions to generate the condition probability [here](https://github.com/MarioniLab/milo_analysis_2020/blob/dc8a30f4025396a17e40ee1708bb023e60a89072/benchmark/benchmark_utils.R#L19-L214) and the wrapper script to make data with synthetic labels from a saved `SingleCellExperiment` object [here](https://github.com/MarioniLab/milo_analysis_2020/blob/main/benchmark/benchmark_make_data/make_bm_data.R).

Hope this helps!

**Comment by mugpeng** [comment]
Thanks, emdann. I got it! :)
