### ISSUE TITLE
About the calculation of neighborhoods logFC in multiple periods

### ISSUE THREAD

**Issue by xiangjiahao1** [MarioniLab/miloR#213]
Thank you for your team's contributions in the field of single cell analysis.
I'm sorry that I don't know the algorithm very well. I have five single-cell samples from A,B,C,D and E. I have a cell type that predominates in phase C. I used miloR for analysis, and this cluster yielded negative log fold changes in many neighborhoods, and plotDAbeeswarm showed that this could not reveal the cell types that dominated the intermediate period. What explains this intermediate cell type? And how log fold change is calculated for multiple periods.

Thanks

**Comment by BioMedInvestorNL** [comment]
Hi. Any news on this? I am also trying to understand how the logFC works (and is calculated) when multiple classes exist in the type evaluated

**Comment by emdann** [comment]
Hi @xiangjiahao1 sorry for missing this. When multiple classes exist in the covariate of interest specified in the design, the last level of that covariate is considered the level of interest and the test is performed in a one-vs-all fashion. E.g. if testing for `condition` with levels `c('A','B','C')`, running `textNhoods(milo_obj, design='~ condition')` will test for C vs rest.
One can specify

**Comment by BioMedInvestorNL** [comment]
Hi. Thank you very much for this clarification.

**Comment by xiangjiahao1** [comment]
> Hi @xiangjiahao1 sorry for missing this. When multiple classes exist in the covariate of interest specified in the design, the last level of that covariate is considered the level of interest and the test is performed in a one-vs-all fashion. E.g. if testing for `condition` with levels `c('A','B','C')`, running `textNhoods(milo_obj, design='~ condition')` will test for C vs rest.
> 
> One can specify the comparison of interest by specifying contrasts. E.g. to compare B vs A
> 
> ```
> testNhoods(milo_obj, design='~ condition', model.contrasts = c("ConditionB - ConditionA"))
> ```
> 
> See [this vignette](https://bioconductor.org/packages/release/bioc/vignettes/miloR/inst/doc/milo_contrasts.html) for a more detailed tutorial.

Thank you for your ansewer.
Can I understand that final logFC value is average logfc (C vs rest)?

**Comment by emdann** [comment]
As described in the [model description](https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-021-01033-z/MediaObjects/41587_2021_1033_MOESM1_ESM.pdf) from our paper
> We use a log-linear model to model the influence of a biological condition on the expected counts in the
neighbourhood:

$$
log \mu_{ns} = \sum_{g=1}^{G} x_{sg}\beta_{ng} + log L_s
$$

> [ $\mu_{n,s}$ = the mean number of cells from sample s in neighbourhood n, $L_s$ = sum of counts
of cells of s over all the neighbourhoods]
> Here, for each possible value g taken by the biological condition of interest, xsg is the vector indicating
the condition value applied to sample s. βng is the regression coefficient by which the covariate effects are
mediated for neighbourhood n, that represents the log fold-change between number of cells in condition g
and all other conditions. 

So in this example $G = \\{A, B, C\\}$ and  the final logFC corresponds to $\beta_{n,C}$
