### ISSUE TITLE
Regarding more than 2 experiment conditions in MiloR

### ISSUE THREAD

**Issue by studymeow** [MarioniLab/miloR#214]
Hi, thank you for bringing this wonderful package. I came across this https://github.com/MarioniLab/miloR/issues/81, you mentioned for more than 2 variables, Milo will only compare the first level and last level, and so does it mean we can only use milo for two experimental conditions?

Thank you!

**Comment by emdann** [comment]
Hi @studymeow, thank you for your interest in using Milo! You can certainly use milo for more than two experimental conditions or for continuous covariates. For the case of multi level covariates you can specify the type of comparison you are interested in by using the option `model.contrasts` in `testNhoods`. This could include both a "one-vs-all" design or a "case-vs-ctrl" design. You can find a vignette to navigate through the use of contrasts in the `devel` branch  https://github.com/MarioniLab/miloR/blob/devel/vignettes/milo_contrasts.Rmd

**Comment by studymeow** [comment]
Thank you! This is super helpful.
