### ISSUE TITLE
Conservative p-value histogram

### ISSUE THREAD

**Issue by NadineBestard** [MarioniLab/miloR#220]
I have a question more on the interpretation side; let me know if this is not the right place for it and where I could post it if not. 

I have a dataset with KO, HETs and WTs Sample. I did a first contrast between KO and WT that worked beautifully. The contrast between HETs and WTs all turned out to be n.s., but I am not trusting these results as this is how the p-values looked like
![image](https://user-images.githubusercontent.com/61509376/170762541-cd2ae8b9-22f9-443c-abb1-676f13873cd9.png)

I have found [this](http://varianceexplained.org/statistics/interpreting-pvalue-histogram/) very helpful article that says: 

> "Do not look at this distribution and say, “Oh, I guess I don’t have any significant hypotheses.” P-values are specifically designed so that they are uniform under the null hypothesis. A graph like this indicates something is wrong with your test." 

What could be wrong with the test?
This is how the design table looks like: 
```
           Sample genotype batch
EKDL2651       WT     3
EKDL2652      HET     3
EKDL2653       KO     3
EKDL2654       WT     4
EKDL2655      HET     4
EKDL2656       KO     4
EKDL2657       WT     5
EKDL2658      HET     5
EKDL2659       KO     5
EKDL2660       WT     6
EKDL2661      HET     6
EKDL2662       KO     6
```
And I used the code below: 

```
da_results <- testNhoods(milo, design = ~ 0 + genotype + batch, design.df = design, model.contrasts = genotypeHET-genotypeWT, reduced.dim = "corrected")
```

**Comment by emdann** [comment]
Hi @NadineBestard,
The p-val histogram looks odd indeed. Did you use the same design formula (`~ 0 + genotype + batch`) in the test for KO vs WT? By default the result table for the milo test stores in the `logFC` column the coefficient of the reference level for the last covariate in the formula (which in this case is `batch`), but the order shouldn't matter when you specify the contrasts...

You might get a histogram like that if you have swapped case and control condition, although the syntax in `model.contrasts` should be correct here. Maybe check that the assignment of cells to samples/genotypes is correct in `colData(milo)`? You could also check whether after tweaking the parameters for graph and nhood building (e.g. increase k) you still get the same distribution. Except for this I don't have many brilliant ideas at the moment, maybe @MikeDMorgan has more suggestions here?

**Comment by NadineBestard** [comment]
Thanks for your quick response,

I did use the same formula for KOvsWT. I also tested to not correct for batch and got a very similar plot. I am not very sure how you were thinking of checking the colData(), but from having a quick look, cells marked with HET genotype also have a HET sample. Plotting the dimreduction from milo object colouring by genotype also looks the same as always. 

I did use the same k for both contrasts (KOvsWT and HETvsWT), and I do not see any reason to change the k but if you think it could help I could give this a try next week. 

I understand that swapping control and case would not be correct biologically, as I would be using the case as a reference; but I don't get why it could yield this distribution of p-values. Out of curiosity I used the contrast `"genotypeWT - genotypeHET"` and I get again all n.s. with a similar p-value distribution. 
![image](https://user-images.githubusercontent.com/61509376/170847375-85b792b3-4030-49f5-801d-bb56108913e9.png)

I also tested HETvsKO and that seemed to work fine. 
![image](https://user-images.githubusercontent.com/61509376/170847347-5ca5dc1a-13a5-40ad-bbd1-686a42b9ffb5.png)

I hope that @MikeDMorgan will be able to bring some light to this situation! 


PS: If I am using the design with batch as the last covariate is because of the error below that appeared when putting this before the genotype. This seemed to have resolved just by swapping the covariates, so I did not spend more time debugging, as you said, it should not matter if I am specifying the contrast. 

<details>
  <summary>Expand error</summary>
  
```
> head(design)
           Sample batch genotype
EKDL2651 EKDL2651     3       WT
EKDL2652 EKDL2652     3      HET
EKDL2653 EKDL2653     3       KO
EKDL2654 EKDL2654     4       WT
EKDL2655 EKDL2655     4      HET
EKDL2656 EKDL2656     4       KO
> contrastKO
[1] "genotypeKO - genotypeWT"
> da_results <- testNhoods(milo, design = ~ 0 + batch + genotype, design.df = design, model.contrasts = contrastKO, reduced.dim = "corrected")
Error in eval(ej, envir = levelsenv) : object 'genotypeWT' not found
4.
eval(ej, envir = levelsenv)
3.
eval(ej, envir = levelsenv)
2.
makeContrasts(contrasts = model.contrasts, levels = model)
1.
testNhoods(milo, design = ~0 + batch + genotype, design.df = design, model.contrasts = contrastKO, reduced.dim = "corrected")
```
</details>

**Comment by MikeDMorgan** [comment]
Hi @NadineBestard This type of histogram that is left-skewed like this is usually indicative of a confounding variable that has not been accounted for in your model. In this case it is something that is probably correlated with your HET samples, e.g. processing batch, sequencing, other experimental handling factor.

**Comment by NadineBestard** [comment]
Hi @MikeDMorgan, thanks for your response. 
How would then it be possible that in KO vs HET that does not cause a problem? 
I am correcting here for the processing batch, I could try to correct for the other experimental factor instead, tissue and see if there is an improvement. ( I can not correct for both as tissue and batch are confounded).

**Comment by MikeDMorgan** [comment]
Hi @NadineBestard - the confounding could be with the het samples specifically, e.g. processing/handling batches, animal groups, different genders, etc. If batch and tissue are 100% correlated then it doesn't matter which one you adjust for in your model. The point here is that there is likely an _unaccounted for_ confounding.

**Comment by NadineBestard** [comment]
Hi, 

Reducing the bin size it became more obvious that the main problem with this p-value histogram is a big pick with p-value of 1. 

![image](https://user-images.githubusercontent.com/61509376/171667006-5f19f7db-f33b-4ad7-977d-1098ef7b9515.png)

This corresponds to nhoods only present in the KO, but absent in WT and HET, so they seem to automatically be assigned p-value of 1, as the comparison can not be made.

I have subsetted the object in order to build the n-hood graph only with the genotypes I was going to use for the DA, and these are the results. (there is still a slight drop on the left side but I think it is much better)

![image](https://user-images.githubusercontent.com/61509376/171672136-1a1dfae9-d643-4d03-a332-77edcba1b9a9.png)

I have seen that in #56  you already discussed the fact that making a new graph was a better option than subsetting just for the DA. It makes perfect sense and seems obvious now, but I did not think about it before. Maybe you could add a sentence somewhere advising that this is the preferred method, even though design.df accepts a df only containing a subset of the available samples? 

PS: I had a thorough thought about other possible confounding factors, but the mice are of the same sex and the samples were sequenced in the same lanes; I couldn't think of anything else that could affect it.
