### ISSUE TITLE
Regarding more than 2 groups, should we adjust the spatialFDR?

### ISSUE THREAD

**Issue by fredust** [MarioniLab/miloR#224]
Hello, thank you for designing the great package.
I also had more than 2 conditions in analysis. In the vignette you mentioned that "If we want to test each of these comparisons then we need to pass them sequentially to testNhoods, then apply an additional multiple testing correction to the spatial FDR values. "
So if I had three groups (A,B and C for example), and I wanted to compare the differences between A-B, A-C, B-C. Should I pass multiple comparisons at the same time, such as `contrast.all<-c('groupA-goupB', 'groupB-groupC', 'groupA-goupC')`? Or should I pass the comparison sequentially to testNhoods and adjust the SpatialFDR by other method (such as BH)?

**Comment by MikeDMorgan** [comment]
Hi @fredust At the moment you would be better off passing each comparison group to `testNhoods` separately, then correct the spatial FDRs for these 3 different tests.

**Comment by MikeDMorgan** [comment]
It should be sufficient to adjust each spatial FDR for the 3 tests performed for each nhood. If you plug in the spatial FDRs to a standard multiple testing function, e.g. `p.adjust()` it will assume that you wish to correct for _all_ input tests <- this would be a massive over-correction.

**Comment by fredust** [comment]
Thank you very much!!!!
