### ISSUE TITLE
'edges' must be numeric or character

### ISSUE THREAD

**Issue by brianpenghe** [MarioniLab/miloR#225]
I was following [this tutorial](https://github.com/MarioniLab/milo_analysis_2020/blob/main/notebooks/milo_in_python.ipynb) but got this error:

![image](https://user-images.githubusercontent.com/4110443/180087154-1cd0eb4a-c6c3-4be8-a360-c2f012cd5fe8.png)

Any ideas?

**Comment by brianpenghe** [comment]
@MikeDMorgan that seems to have fixed it. At least no error messages

**Comment by MikeDMorgan** [comment]
Glad that worked - the vignette will just need updating.

**Comment by brianpenghe** [comment]
And is this related to this https://github.com/MarioniLab/miloR/issues/16 ?
