### ISSUE TITLE
A questions about generating simulation data

### ISSUE THREAD

**Issue by ZhenjiangFan** [MarioniLab/miloR#230]
Hi,

Thank you for the amazing work.

I noticed that you used "dyntoy" to generate simulation data and you privided some simulation data under the "data" folder. However, I did not find any code for generating conditions' probabilities for all the cells and assigning the conditions to each cell.
I would like to recreate the procedure, but before that, I think I am wondering if the code can be made accessible to us. It is totelly fine if it is not possible. And any suggestions would be appreciated.

Thank you.

**Comment by MikeDMorgan** [comment]
Hi @ZhenjiangFan as noted in the manuscript - the simulation and analysis code is located at https://github.com/MarioniLab/milo_analysis_2020

The code to generate the simulations can be found in the `simulations` subfolder.

**Comment by ZhenjiangFan** [comment]
Thank you so much. I must have not noticed the link in the manuscript. Sorry about that.

Thank you.
