### ISSUE TITLE
What's the meaning of '5 x N_samples' ?

### ISSUE THREAD

**Issue by altairwei** [MarioniLab/miloR#231]
In the tutorial [Differential abundance testing with Milo - Mouse gastrulation example](https://bioconductor.org/packages/release/bioc/vignettes/miloR/inst/doc/milo_gastrulation.html), you say:

> As a rule of thumb we want to have an average neighbourhood size over 5 x N_samples.

But I'm not sure what it means exactly? Is it five times the number of samples in the dataset?

**Comment by MikeDMorgan** [comment]
Yes

**Comment by qianxu05172019** [comment]
Thank you for creating milo, I love this tool. 
One follow-up question on the neighborhood sizes: 
So my understanding is that we should keep the neighbourhood sizes at ~75, is that correct?
