### ISSUE TITLE
Reproducibility of tutorial

### ISSUE THREAD

**Issue by mdeea** [MarioniLab/miloR#232]
Hi there,

Thanks for this great idea. I'd really like to use this package.
Thanks also for the great Tute.
However, I'm having trouble reproducing your Mouse gastrulation tutorial for V1.5 of Milo with version 1.5 on my R instance.

Maybe you need to set.seed() a few more times during the analysis??

2 Visualize the data
Firstly, while my umap looks similar, it's different, so maybe a seed needs to be explicity set here before calculating the umap?

3.3 Defining representative neighbourhoods on the KNN graph
After creating & plotting Nhoods, the result is similar but not the same,
so again there seems to be a stochastic process invoked in makeNhoods(), so maybe a seed needs to be set prior in the tutorial also?

Section 4
set.seed for another umap?

In 5.1 I ended up with 9 neighbourhood groups instead of the 8 found in the tute.
On this run, My 4 seems to correspond to your 3.
I'm having difficulty working out which group most closely resembles your group 5 for the next bit of the exercise.

After changing the parameters and setting the seed, I've got 10 groups compared to your 13.

5.2 Finding gene signatures for neighbourhoods

Top 5 HVGs are the same

Then it says in the text:
"If you already know you are interested only in the markers for group 2, you might want to test just 8-VS-all using the subset.groups parameter:"
but the code refers to group 5??

In section 5.3
It says it's selecting marker genes for group 10 in the text but group 5 in the code?
and my graph looks completely different.

It would be great if you set the seed for a few more stochastic processes, so users can reproduce your report exactly and thus be confident  they've got the right version of the package loaded etc.

Thanks again.

**Comment by MikeDMorgan** [comment]
Thanks @mdeea for pointing out these issues - we'll get them fixed for the next Bioc release in November.
