### ISSUE TITLE
What if I don't see a significant difference in abundance?

### ISSUE THREAD

**Issue by jbrandst7** [MarioniLab/miloR#238]
Is there a statistic that miloR provides to evaluate power? If I don't see a significant difference in abundance between groups across neighborhoods (which was expected biologically), is there a way I can know that it wasn't just because I needed more replicates in each condition? Thanks for your help!

**Comment by emdann** [comment]
Hi @jbrandst7 
We don't have implemented functions or stats for power analysis at the moment. We discuss sensitivity limitations in the benchmarking sections of our paper (see [Extended Data Fig. 2a](https://www.nature.com/articles/s41587-021-01033-z#Fig7), Suppl. Fig. 4 and [Supplementary note 3.3](https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-021-01033-z/MediaObjects/41587_2021_1033_MOESM1_ESM.pdf))

**Comment by jbrandst7** [comment]
Thanks for your response. Do you know what we would need to do to try to calculate this for ourselves?
