### ISSUE TITLE
Beyond Pairwise Comparisons

### ISSUE THREAD

**Issue by jfouyang** [MarioniLab/miloR#240]
I am just wondering if it is possible to go beyond comparing cell abundance in a pairwise fashion. That is, is it possible to modify the underlying GLM to do comparisons across multiple groups i.e. instead of performing a LRT across >2 groups instead of doing a QL F-test?

**Comment by emdann** [comment]
Hi @jfouyang, not sure this answers your question, but you can specify the classes to compare using the `model.contrasts` argument, also explained here https://github.com/MarioniLab/miloR/issues/213#issuecomment-1265142975 and [see vignette](https://github.com/MarioniLab/miloR/issues/213#issuecomment-1265142975)

**Comment by jfouyang** [comment]
Hey I think that answers my question! Thanks!
