### ISSUE TITLE
Milo constructor does not accept table of counts

### ISSUE THREAD

**Issue by constantAmateur** [MarioniLab/miloR#242]
The documentation for `Milo` says the `...` argument says:

  ``` Arguments passed to the Milo constructor to fill the slots of the base class. This should be either a SingleCellExperiment or matrix of features X cells```

However, if a matrix of features X cells is provided, the function will not execute either of the milo construction entries and will either return:

```Error in Milo(toc) : object 'milo' not found```

Or worse still, if there happens to be an object named `milo` in the global environment, this will be returned instead.  This is because the function checks only for the presence of no input provided, or a `SingleCellExperiment` class object.

**Comment by emdann** [comment]
Thank you @constantAmateur for spotting this! I've opened a patch for this
