### ISSUE TITLE
Plot the number of neighboring cells per condition and neighborhood.

### ISSUE THREAD

**Issue by nickhir** [MarioniLab/miloR#244]
First of all, thank you very much for creating this amazing tool! 

While using it, I sometimes found it very useful, to plot the number of neighboring cells for a given neighborhood that I was interested in. An "interesting" neighborhood could for example be a neighborhood which shows a large logFC, but which is not significantly enriched for any condition. 

So I created a function which does that for me. The result is a `ggplot` which looks like this (red bar is the mean):

![nhood_counts](https://user-images.githubusercontent.com/49643134/194861383-69a5658b-15b2-4346-ac70-de09dd93979e.png)

Let me know if you think that this is a function worth adding to the package. If so, I would open a pull request. 

Cheers!

**Comment by emdann** [comment]
Hey @nickhir, thank you for sharing! I also frequently do this myself but never found the time to add to the R package :) if you have time to open a PR I would be very happy to review and add this plotting function.

**Comment by nickhir** [comment]
Sounds great :)! I have opened a PR to the `devel` branch.
