### ISSUE TITLE
Easier access to changing colors in the plotNhoodGraphDA

### ISSUE THREAD

**Issue by RolantusdataExp** [MarioniLab/miloR#245]
Hi developer team, 

Thank you so much for a great tool! 

I am trying to change the node colors in the plotNhoodGraphDA, as I would like to change the scalebar over the logFC. Default is low = red, high = blue, but would like to change it to the opposite. Can you be of any assistance here? Think it would be useful to add an argument for this (as it is not a ggplot object, but a ggraph object it seems more difficult) 

Best regards, 
Peter

**Comment by emdann** [comment]
Hi @RolantusdataExp, the output of `plotNhoodGraphDA` is a normal ggplot object and you should be able to modify scales (in this case `scale_fill`) as you like it. Following the example from the [basic vignette](https://bioconductor.org/packages/release/bioc/vignettes/miloR/inst/doc/milo_demo.html):
```
traj_milo <- buildNhoodGraph(traj_milo)
plotNhoodGraphDA(traj_milo, da_results, alpha=0.05) +
  scale_fill_gradient2(high='yellow', mid='green')
```
![milo_example](https://user-images.githubusercontent.com/32264060/195104521-1f3c906c-c6a0-4739-8322-0d599d3b98eb.png)
