### ISSUE TITLE
testNhoods performance

### ISSUE THREAD

**Issue by BioMedInvestorNL** [MarioniLab/miloR#249]
Hi,

I really like your tool. But I am having some performance issues I would like your suggestion if I could speed things up. I have a large dataset, around 1kk cells. In this dataset I have multiple clinical meta.data columns I would like to compare in multiple combinations.

My initial plan was to run the  graph generation and neighborhood identification  in the full dataset. After initial problems with the buildGraph and makeNhoods, I adjusted my K and prop, which sped things up.

I have included "dummy" meta data columns which combined different columns creating unique groups, so I could compare those using testNhoods. However, I had trouble with it. It was impossible to run on my instance (aws 384gb, 48 cores), as it kept on crashing.

I decided then to subset my data. I have now around 200k cells, but the testNhoods still takes very long (and I am not sure it will finish without crashing). I have it running for 3h+. I could not find an easy way to speed it up, any suggestions?

I pasted below how I ran my commands.

Any help would be appreciated

```{r}
data.set<- buildGraph(data.set, k = 40, d = 30) #Build KNN graph

data.set<- makeNhoods(data.set, prop = 0.05, k = 40, d=30, refined = TRUE) #Defining the neighbors

```

#################### 

traj_design <- data.frame(colData(data.set))[,c("Patient_Tissue", "Tissue_origin_adjusted")]
traj_design <- distinct(traj_design) # adjust table to experimental design

traj_design
rownames(traj_design) <- traj_design$Patient_Tissue
traj_design <- traj_design[colnames(nhoodCounts(data.set)), , drop=FALSE]
table(traj_design$Tumor.msi)

model <- model.matrix(~ 0 + Tissue_origin_adjusted, data=traj_design)
Contrast1.contrast <- c("Tissue_origin_adjustedNormal - Tissue_origin_adjustedTumor")
mod.constrast <- makeContrasts(contrasts=Contrast1.contrast, levels=model)

mod.constrast
da_results_MSI <- testNhoods(data.set, design = ~ 0 + Tissue_origin_adjusted, design.df = traj_design, model.contrasts = Contrast1.contrast,fdr.weighting="k-distance")

**Comment by MikeDMorgan** [comment]
First, thanks for using Milo. Second, please post the output of your `sessionInfo()` so that we know what version of the package you are using.

**Comment by BioMedInvestorNL** [comment]
Sorry for the delay. I stopped the run after 10h.

here is the output of sessionInfo()

<html>
<body>


R version 4.1.1 (2021-08-10) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 18.04.5 LTS  Matrix products: default BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3 LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3  locale: [1] C  attached base packages: [1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] patchwork_1.1.1             dplyr_1.0.7                 scater_1.20.1               ggplot2_3.3.5                [5] scuttle_1.2.1               SingleCellExperiment_1.14.1 SummarizedExperiment_1.22.0 Biobase_2.52.0               [9] GenomicRanges_1.44.0        GenomeInfoDb_1.28.1         IRanges_2.26.0              S4Vectors_0.30.0            [13] BiocGenerics_0.38.0         MatrixGenerics_1.4.3        matrixStats_0.60.1          miloR_1.0.0                 [17] edgeR_3.34.1                limma_3.48.3                SeuratObject_4.0.2          Seurat_4.0.4                [21] BiocManager_1.30.16          loaded via a namespace (and not attached):   [1] utf8_1.2.2                reticulate_1.20           tidyselect_1.1.1          htmlwidgets_1.5.3           [5] grid_4.1.1                BiocParallel_1.26.2       Rtsne_0.15                devtools_2.4.5              [9] munsell_0.5.0             ScaledMatrix_1.0.0        codetools_0.2-18          ica_1.0-2                  [13] statmod_1.4.37            future_1.22.1             miniUI_0.1.1.1            withr_2.5.0                [17] colorspace_2.0-2          knitr_1.33                rstudioapi_0.13           ROCR_1.0-11                [21] tensor_1.5                listenv_0.8.0             labeling_0.4.2            GenomeInfoDbData_1.2.6     [25] polyclip_1.10-0           farver_2.1.0              parallelly_1.27.0         vctrs_0.3.8                [29] generics_0.1.0            xfun_0.25                 R6_2.5.1                  ggbeeswarm_0.6.0           [33] graphlayouts_0.7.1        rsvd_1.0.5                locfit_1.5-9.6            bitops_1.0-7               [37] spatstat.utils_2.2-0      cachem_1.0.6              DelayedArray_0.18.0       assertthat_0.2.1           [41] promises_1.2.0.1          scales_1.1.1              ggraph_2.0.5              beeswarm_0.4.0             [45] gtable_0.3.0              beachmat_2.8.1            globals_0.14.0            processx_3.5.2             [49] goftest_1.2-2             tidygraph_1.2.0           rlang_1.0.6               splines_4.1.1              [53] lazyeval_0.2.2            spatstat.geom_2.2-2       reshape2_1.4.4            abind_1.4-5                [57] httpuv_1.6.2              tools_4.1.1               usethis_2.1.6             ellipsis_0.3.2             [61] spatstat.core_2.3-0       RColorBrewer_1.1-2        sessioninfo_1.2.2         ggridges_0.5.3             [65] Rcpp_1.0.7                plyr_1.8.6                sparseMatrixStats_1.4.2   zlibbioc_1.38.0            [69] purrr_0.3.4               RCurl_1.98-1.4            ps_1.6.0                  prettyunits_1.1.1          [73] rpart_4.1-15              deldir_0.2-10             pbapply_1.4-3             viridis_0.6.1              [77] cowplot_1.1.1             urlchecker_1.0.1          zoo_1.8-9                 ggrepel_0.9.1              [81] cluster_2.1.2             fs_1.5.2                  magrittr_2.0.1            data.table_1.14.0          [85] scattermore_0.7           lmtest_0.9-38             RANN_2.6.1                fitdistrplus_1.1-5         [89] pkgload_1.3.0             mime_0.11                 xtable_1.8-4              gridExtra_2.3              [93] compiler_4.1.1            tibble_3.1.4              KernSmooth_2.23-20        crayon_1.4.1               [97] htmltools_0.5.3           mgcv_1.8-36               later_1.3.0               tidyr_1.1.3               [101] DBI_1.1.1                 tweenr_1.0.2              MASS_7.3-54               Matrix_1.3-4              [105] cli_3.4.1                 igraph_1.2.6              pkgconfig_2.0.3           plotly_4.9.4.1            [109] spatstat.sparse_2.0-0     vipor_0.4.5               XVector_0.32.0            stringr_1.4.0             [113] callr_3.7.0               digest_0.6.27             sctransform_0.3.2         RcppAnnoy_0.0.19          [117] spatstat.data_2.1-0       leiden_0.3.9              uwot_0.1.10               DelayedMatrixStats_1.14.3 [121] shiny_1.6.0               gtools_3.9.2              lifecycle_1.0.3           nlme_3.1-152              [125] jsonlite_1.7.2            BiocNeighbors_1.10.0      viridisLite_0.4.0         fansi_0.5.0               [129] pillar_1.6.2              lattice_0.20-44           fastmap_1.1.0             httr_1.4.2                [133] pkgbuild_1.3.1            survival_3.2-11           glue_1.4.2                remotes_2.4.2             [137] png_0.1-7                 ggforce_0.3.3             stringi_1.7.3             profvis_0.3.7             [141] BiocSingular_1.8.1        memoise_2.0.1             irlba_2.3.3               future.apply_1.8.1
--
 
> | >
>


</body>
</html>

**Comment by MikeDMorgan** [comment]
OK - you're running a very old version of Milo. Please upgrade to v1.5 through Bioconductor first.  The reason for it being so slow is that you are computing a huge number of distances which are required for both the neighbourhood refinement and computing the spatial FDR.

For large datasets like yours, we have introduced a new approximation to both these steps, which can be used thus:

* Use `makeNhoods(..., refinement_scheme="graph")` instead - this uses an approximation to the Euclidean distances using the number of triangles on the graph connected to each cell
* Run `testNhoods(..., fdr.weighting="graph-overlap")` - this uses the number of overlapping cells between nhoods to estimate the spatial FDR correction factor.

**Comment by BioMedInvestorNL** [comment]
Hi Mike. Sorry for the delay. It does work this way. thank you very much.

One last question: do you have specific recommendations related to the neighborhood size for these large dataset adaptations? I've been playing around with that, but I am not sure what would the optimal parameters.

**Comment by BioMedInvestorNL** [comment]
Hi Mike,

I was reading that this morning actually. In my case I have around 90 samples (50 from experimental group, 40 from control) . So I should have neighborhoods of around 450 cells. But to obtain that I would need to go to K values above the suggested 50 threshold. Is that correct? Do you think that should be ok?

**Comment by MikeDMorgan** [comment]
There is a trade-off between the resolution of nhoods with a larger k and the numbers of cell counts for a given sample. If k is too small you'll end up with sparse counts, which will introduce too much variance into the GLM and you'll have much lower power. However, too high a k will lose resolution to identify subtle/rare cell state changes. The numbers we give are a guideline - you as the analyst are responsible for the final decisions. We recommend an iterative approach that involves varying k to find a range over which the results do not change appreciably. If you have a positive control change in your experiment (which every proper experiment should have), then you can use this as a guide.

As to the fact that your total numbers of cells per sample spans 2 orders of magnitude - I would strongly recommend doing some QC on the numbers of cells captured - 200 hundred cells from a sample isn't really going to add much. The GLM does normalise for differences between samples _assuming this is uncorrelated with your experimental design_. I.e. if your experimental group systematically has many fewer cells (order of magnitude) then you may run into issues. This can be investigated by making an MAplot of your results - if you see a considerable off-horizontal deviation then you have a problem which can only really be remedied by down-sampling your cells to be more even across conditions (or removing the top and bottom samples in pairs until you don't have such a drastic deviation anymore).

**Comment by SoManyPepople** [comment]
> 



> OK - you're running a very old version of Milo. Please upgrade to v1.5 through Bioconductor first. The reason for it being so slow is that you are computing a huge number of distances which are required for both the neighbourhood refinement and computing the spatial FDR.
> 
> For large datasets like yours, we have introduced a new approximation to both these steps, which can be used thus:
> 
> * Use `makeNhoods(..., refinement_scheme="graph")` instead - this uses an approximation to the Euclidean distances using the number of triangles on the graph connected to each cell
> * Run `testNhoods(..., fdr.weighting="graph-overlap")` - this uses the number of overlapping cells between nhoods to estimate the spatial FDR correction factor.

Hi Mike, 

Thanks for your kind advices. These seems work well for me too.  
But I want to make sure: if i use 'refinement_scheme="graph"' option for makeNhoods, which uses an approximation of Euclidean distances (Likely, this distances were calculated via the 'calcNhoodDistance()' function between 'makeNhoods()' and 'testNhoods()'. And I actually stucked at this calcNhoodDistance step for more than 24 hours given ~900k cells and ~40k identified nhoods), I don't need to run 'calcNhoodDistance()' before `testNhoods(..., fdr.weighting="graph-overlap")`, right?

**Comment by MikeDMorgan** [comment]
Yes, using the graph-only approach makes `calcNhoodDistance` redundant.
