### ISSUE TITLE
Differential abundance and subclustering

### ISSUE THREAD

**Issue by dgagler** [MarioniLab/miloR#250]
Hi guys,

Thanks again for making a great package with a lot of utility. I'm wondering if you have any suggestions for using Milo during a subclustering analysis. 

I've run Milo on my dataset and determined some interesting differences in abundance for NK cells between my conditions. I'm now trying to explore NK cells in more detail. I've performed a subclustering analysis on my NK cells, running a new PCA and clustering, and would like to rerun Milo on these NK cells only, as opposed to the full dataset. Is this something that you guys have used Milo for? Do you have any thoughts on this approach in general? 

And assuming this doesn't immediately horrify you, would you recommend using the same K and D values for a subset analysis as was used for the full dataset? I've messed around with some values and it seems like changing K does not significantly affect the results, but it does change the neighborhood size (obviously) past where you guys recommend (median nhood size > 5 * number of samples). Furthermore, I reran a PCA and clustering on my NK cell subset and have been using D = # of PCs instead of the D value associated with the PCA from the full dataset. Hope this all makes sense. Interested in a methodological reality check here and whether you think this approach is sound.

Thanks,
Dylan

**Comment by MikeDMorgan** [comment]
Hi Dylan,
This is a totally legitimate approach to take - we do the same thing in the Milo paper to investigate liver cirrhosis in more detail. I don't think that you necessarily need to retain the same values of k and D as you aren't trying to compare the two graphs or results.
