### ISSUE TITLE
ggbeeswarm is getting de-archived from CRAN

### ISSUE THREAD

**Issue by MikeDMorgan** [MarioniLab/miloR#253]
This is a heads-up @emdann that ggbeeswarm is getting removed from CRAN because the maintainers having fixed on-going issues. We'll need to either implement our own alternative for the beeswarm plots or find a suitable alternative.

**Comment by emdann** [comment]
😱 😱 😱

**Comment by MikeDMorgan** [comment]
Quite a few other Bioconductor packages use it so it's gonna hit quite a few packages 😬

**Comment by MikeDMorgan** [comment]
Following some to-and-fro the CRAN version has been fixed thankfully.
