### ISSUE TITLE
Continuous variables and ANOVAs?

### ISSUE THREAD

**Issue by dagarfield** [MarioniLab/miloR#254]
Not a bug....and not quite a features request....but still something I'd like help with :)

Big fan of Milo -- been using it for a range of analyses, and recently noticed that the DA tests sit on top of EdgeR, which suggests that a range of tests are possible beyond the bivariate cases given in the gastrulation tutorial. 

**1. Continuous variable tests.** 
Presumably this is as simple as including a continuous variable and putting it last in the design. e.g. 
`da_results <- testNhoods(sce_milo, design = ~ group + treatment_days, design.df = my_design)`

Right?

**2. ANOVAs**
It would be nice to be able to evaluate *if* a given variable has an effect on proportion in cases of multilevel experimental factors. Is there a way to specify such a model? I gave it a try with the following:
`da_results3 <- testNhoods(sce_milo, design = ~ treatment_length + week_group, design.df = my_design)`
where the first term (treatment_length) is two levels and the second (week_group) is three levels and I'd like to know if `week_group` has any effect at all (or, more properly, if there are any proportion differences among the groups). 

Is this possible?

Thanks!

**Comment by MikeDMorgan** [comment]
Hi @dagarfield. You are correct in the treatment of continuous variables - if you don't have obvious ordering of levels in a variable you can also use contrasts, which we describe in this vignette: [milo_contrasts.Rmd](https://github.com/MarioniLab/miloR/blob/1d2d488ab514075287ec42b242b0bf556e385ed3/vignettes/milo_contrasts.Rmd)

As for performing ANOVA - we don't currently have plans to introduce an explicit ANOVA function into Milo as the goal is to detect differential abundance, which by definition is a comparative approach. You could try to set this up with multiple different 1 vs. all contrasts, 1 for each level of your group variable and compare the p-values, or you could try a likelihood ratio test of the full model with the group variable vs just the intercept as suggested by [Devon Ryan on Biostars (this is actually for DESeq2, but the concept _should_ work).](https://www.biostars.org/p/151857/#151888). If you're familiar with how edgeR works then you can feed the nhood counts matrix and model matrix in yourself - look at the testNhoods.R code for inspiration. You'll need to comptue the spatial FDR as well, but this function is accessible for just this reason.
