### ISSUE TITLE
Milo reccomendation for homogenous or differentiated sample

### ISSUE THREAD

**Issue by emanuelavilla** [MarioniLab/miloR#257]
Hello!

I would like to ask if Milo could be used in more homogeneous samples (such as hematopoietic stem cells) or just for very differentiated samples. 

This is because I'm trying to use Milo but I cannot find any significant differential abundance between the 2 conditions I am testing in a very homogeneous sample.

Thanks!

**Comment by MikeDMorgan** [comment]
Hi @emanuelavilla there is no restriction on cellular heterogeneity. If there is no differential abundance then there could be any number of reasons why - more or less heterogeneity wouldn't be my first thing to question though. You need to consider the sample sizes, how different your conditions actually are, what positive/negative controls are in the experiments, etc.
