### ISSUE TITLE
Easily access which cells belong to which neighbourhoods

### ISSUE THREAD

**Issue by caitsimop** [MarioniLab/miloR#258]
First of all, thank you so much for this awesome package! 

I'm wondering if there's a function that gives some sort of data frame that connects cells to neighbourhoods/neighbourhood groups? I'm looking to do some custom downstream analyses, but am having difficulty connecting cells to neighbourhoods. 

I'm likely missing an option/output df, so forgive me if this answer is right in front of me.

Thanks in advance!

**Comment by emdann** [comment]
Hi @caitsimop, thank you for using Milo! You can access the assignment of cells to neighbourhoods by running `nhoods(milo)` (in the form of a binary matrix of dimensions n_cells x n_nhoods)

**Comment by caitsimop** [comment]
Wow, what a quick response :) Thank you so much @emdann!
