### ISSUE TITLE
List of cells that are part of a neighbourhood of interest highlighted by testNhoods()

### ISSUE THREAD

**Issue by GAgafencu** [MarioniLab/miloR#260]
Thank you so much for developing this package!
I'm wondering if there's a way to identify which cells are part of a specific neighbourhood that has highlighted following running testNhoods() as being differentially abundant while comparing one condition versus another one?
One of the neighbourhoods of interest identified using testNhoods() has a name as highlighted in the NHood column in the output of the previously mentioned function that I can't find among the neighbourhoods that are listed in the output of the nhoods() function run on the Milo object that was used as imput for the testNhoods() function.
Could you please help me identify the cells that are part of a specific neighbourhood identified using the testNhoods() function?

Thank you for your time and help

**Comment by emdann** [comment]
Hi @GAgafencu, the column names of `nhoods(milo.obj)` come from the index cell (i.e. the cell sampled to build the neighbourhood, which you can also extract running `nhoodIndex(milo.obj)`). The order of nhoods in `nhoods(milo.obj)` columns is the same as the rows in the output of `testNhoods`.

So you can get the cells in a neighbourhood of interest like so:
```
nhood_of_interest <- milo.res[milo.res$SpatialFDR < 0.1,]$Nhood[1]
cells_in_nhood <- nhoods(milo.obj)[,nhood_of_interest] > 1
```

**Comment by GAgafencu** [comment]
Thank you for the quick reply! I'll look into this solution and see if it will solve the issue.
