### ISSUE TITLE
Design matrix not full rank - mixture of paired and unpaired samples

### ISSUE THREAD

**Issue by kane9530** [MarioniLab/miloR#263]
Dear miloR developers,

Thank you for this excellent package, which I am currently using to analyse my scRNA-seq data.

My question is more of a stats / design matrix issue than a miloR-related question, but I was wondering if you could help!

Currently, I have a dataset that looks like this (first 10 of 13 rows):
<img width="193" alt="Screenshot 2023-02-06 at 5 45 01 PM" src="https://user-images.githubusercontent.com/15279664/216939456-0dc1d4e9-1255-43b5-a77b-ce23220e4087.png">

I wish to run a DA analysis between the "polyp" and "adenocarcinoma" conditions.

As you can see, most of the donors contribute only the "polyp" or "adenocarcinoma" conditions, but 2 of them, **A001** and **A015** are paired and contribute to both conditions. When I run _countCells_ and then _nhoodCounts_, I get a sparse matrix with 11 columns returned. However, when I try to create the design matrix, I use the metadata as in the above screenshot, which consists of 13 rows. Indeed, I cannot assign "Donor" as the row names, since they are not unique.

Currently, my crude solution is to simply discard one of the conditions from **A001** and **A015** to make the matrix full rank (11 columns total). Perhaps I could include an extra articificial column specifically to distinguish between these 2 sample conditions? (e.g. 2 for A001_polyp and A015_polyp and 1 for the rest), but my line of reasoning is still fuzzy and I am not sure where to include this information.

I wonder if you could suggest an alternate solution for this! 

Best wishes,
Kane

**Comment by MikeDMorgan** [comment]
Hi @kane9530 Thanks for using Milo. In this situation where you are comparing across tissues/cancer grades/stages then it makes sense to split the donors that have cells derived from both into separate samples. The slight issue here then is that these are not strictly independent and identically distributed (iid) samples (they are dependent when they come from the same donor). 

I think you've basically landed on the two ways to address this:
* only use one tissue from either donor - you could compare the analyses for different combinations of which donor tissue sample is included if you are concerned about sensitivity, e.g., one donor contains many more cells than the other.
* create the additional 2 "samples" by splitting the adenocarcinoma & polyps into separate samples for these 2 donors, then add a variable to the model that marks only the samples that come from the same donor. This will adjust the mean effect, though it doesn't strictly handle the dependence structure.

The small number of donors with multiple tissues is the main problem - if they all had multiple samples you could include a the donor ID in the model to allow for pairing. Unfortunately, this won't work in this case as you'd use all of your degrees of freedom. From a purely statistical model point of view, dropping one of each sample would correctly address the issue and wouldn't violate the iid assumption of the GLM.
