### ISSUE TITLE
Error in comparison of two samples

### ISSUE THREAD

**Issue by Yingjie848** [MarioniLab/miloR#264]
I am using miloR to compare two samples, one is WT and another one is KO, my design matrix is like below:

> model_matrix(traj_design,sample ~ genotype)
  `(Intercept)` genotypeKO
1             1          0
2             1          1

My traj_design table:
rownames          sample genotype
WT    WT        WT
KO     KO         KO

When I run testNhoods: testNhoods(milo, design = ~ genotype, design.df = traj_design)
I get this error:

   Using TMM normalisation
   Error in glmFit.default(y, design = design, dispersion = dispersion, offset = offset,  : 
     NA dispersions not allowed
   In addition: Warning message:
   In estimateDisp.default(y = y$counts, design = design, group = group,  :
     No residual df: setting dispersion to NA

May I know why I have NA dispersions? Is that because I don't have replicates?

Thank you!

**Comment by MikeDMorgan** [comment]
Hi @Yingjie848 Milo is designed only for replicated single cell experiments. You can't infer differential abundance without multiple samples.

**Comment by YichaoOU** [comment]
Hi @MikeDMorgan ,

Can we randomly split one sample into two replicates?

Thanks,
Yichao

**Comment by MikeDMorgan** [comment]
No - they aren't independent replicates then. That is fundamentally wrong. I __strongly__ advise you familiarise yourself with the basics of experimental and study design before proceeding any further.

**Comment by YichaoOU** [comment]
@MikeDMorgan I thought each cell is independent. That's why we can make pseudo-replicates? Similar to pseudo-bulk analysis?

Thanks,
Yichao

**Comment by MikeDMorgan** [comment]
No, that's a fundamental misunderstanding - cells are not independent replicates - making pseudo-replicates is not valid in this instance. Pseudo-bulking is to aggregate over cells _for each replicate_. If you collect the cells from the same individual they have a dependency on that individual organism.
