### ISSUE TITLE
Milo R for scATAC seq 

### ISSUE THREAD

**Issue by emanuelavilla** [MarioniLab/miloR#273]
Hello!

Thanks for the tool! It is very useful for my research!

I would like to ask if it would be possible to run Milo for scATAC seq data analysed by Signac package.

**Comment by MikeDMorgan** [comment]
Hi @emanuelavilla Milo is agnostic to the data type, as long as it fits into the paradigm of features X cells as a `SingleCellExperiment`/`Milo` object and the data can be represented by a NN-graph, then nothing should stop you using Milo for scATAC-seq. Bear in mind that all of the usual caveats and assumptions still apply. We haven't explicitly tested Milo on scATAC-seq data ourselves - so we can't make any guarantess - but I don't see why it shouldn't apply.

There will almost certainly be some features of scATAC-seq, i.e., high sparsity, many features that might impact on the graph and subsequent DA testing.

**Comment by emanuelavilla** [comment]
Thanks!

I already tried applying Milo R to my scATAC data by adding the dimensional reduction when building the KNN graph. 

ATAC.milo <- buildGraph(ATAC.milo, 
                       k = 20, #number of dimensions of PCA
                       d = 20, 
                       reduced.dim = 'INTEGRATED_LSI')

And the result we obtained is the one we expected. So, it works!

**Comment by MikeDMorgan** [comment]
Great to hear!
