### ISSUE TITLE
Should I consider RNA assay or Integrated Assay for Milo

### ISSUE THREAD

**Issue by deconvolute** [MarioniLab/miloR#275]
I have performed Integration using Seurat. Should I consider the RNA or Integrated Assay for Milo analysis??

**Comment by MikeDMorgan** [comment]
It 100% depends on your research question - Milo is agnostic to the modality.

**Comment by deconvolute** [comment]
I am getting two extreme results while running Milo with RNA and Integrated assay.

Results from Integrated assay: 
<img width="620" alt="MiloR_Integration" src="https://user-images.githubusercontent.com/114025279/225336027-99bcd437-1f94-4787-9619-46aea76f3184.png">


Results from RNA assay: 
<img width="882" alt="MiloR_RNA_assay" src="https://user-images.githubusercontent.com/114025279/225336032-2dd93204-0cba-484f-8107-d2db6983e34d.png">

Please let me know your thoughts on it.

**Comment by AteeqMKhaliq** [comment]
Hi Mike, This is what we got when we ran milo, we got two different results on the same cells! 
Dr Ateeq Khaliq
IUPUI, Indiana.

**Comment by MikeDMorgan** [comment]
Hi @AteeqMKhaliq  - these are 2 different NN-graphs, that means the underlying connectivity and thus neighbourhood composition is different. It doesn't matter that these are the same cells. Again, this is a function of the data, and the multi-modal integration, not Milo or differential abundance testing. I suggest you examine the differences in the integration to resolve this conundrum.
