### ISSUE TITLE
Plotting LFC without filtering by FDR

### ISSUE THREAD

**Issue by Dario-Rocha** [MarioniLab/miloR#282]
Being able to quantify the changes in abundances independently from the clustering is a very welcomed feature, even when no statistical tests are performed (for example when we have only two samples). Therefore, showing the logFC by neighbourhood, without setting as '0' those neighbourhoods with too high of a FDR value can be desirable. To achieve this in a simple way, I've modified your plotNhoodGraphDA function, so I am sharing this with you in case it's useful for anybody who reads this post.

f_plotNhoodGraphDA <- function (x, milo_res, alpha = 0.05, res_column = "logFC", filterbyFDR = TRUE, ...) 
{
  if(filterbyFDR){
    signif_res <- milo_res
    signif_res[signif_res$SpatialFDR > alpha, res_column] <- 0
    colData(x)[res_column] <- NA
    colData(x)[unlist(nhoodIndex(x)[signif_res$Nhood]), res_column] <- signif_res[, res_column]
  } else {
    signif_res <- milo_res
    colData(x)[res_column] <- NA
    colData(x)[unlist(nhoodIndex(x)[signif_res$Nhood]), res_column] <- signif_res[, res_column]
  }
  
  plotNhoodGraph(x, colour_by = res_column, ...)
}

**Comment by MikeDMorgan** [comment]
Thanks @Dario-Rocha However, raising this as an issue isn't really the right place to do this, unless you want to make this an explicit feature request. In which case you need to flag it as such and read the Contribution section of the repo README.
