### ISSUE TITLE
findNhoodMarkers mixing Gene names

### ISSUE THREAD

**Issue by Dario-Rocha** [MarioniLab/miloR#283]
The rownames of the object returned by findNhoodMarkers does not match the GeneID column of the same object. Somewhere the names are getting mixed and I am not sure where, and which are the real GeneIDs.

```
a_results_blood_t <- testNhoods(a_milo, 
                                 design = ~ 0 + tissue, 
                                 design.df = a_design,
                                 model.contrasts = a_all_contrasts[2],
                                 reduced.dim = 'PCA')

a_dge <- findNhoodMarkers(a_milo, a_results_blood_t,
                          gene.offset = FALSE, da.fdr = 0.1,
                          aggregate.samples = TRUE, sample_col = "orig.ident",
                          subset.nhoods = a_results_blood_t$annot %in% c("Treg_1")
)

head(a_dge, 1)

```
> logFC_1  adj.P.Val_1    logFC_2  adj.P.Val_2     logFC_3  adj.P.Val_3   logFC_4  adj.P.Val_4   GeneID
> TBC1D4 0.33066146 9.106869e-15 -0.4461094 2.320066e-15  0.31301019 1.513552e-15 0.7330791 9.978614e-23  HLA-DRA

**Comment by MikeDMorgan** [comment]
When posting an issue, please provide the output of your `sessionInfo()`, and ensure that you are using the most up to date version of Milo from Bioconductor. If this persists then flag it as a bug and we'll take a look.
