### ISSUE TITLE
Include batch as a covariate or use batch-corrected latent space for constructing KNN graph

### ISSUE THREAD

**Issue by lucygarner** [MarioniLab/miloR#286]
Hi,

We have a large PBMC dataset that was generated across 7 batches. Each batch has a mix of donors from different conditions (not perfectly balanced across the batches). We see some batch effects in the UMAP that can be corrected using Harmony. I was wondering whether it is preferable to use Harmony-corrected data for constructing the KNN graph or to include batch as a covariate in the model? Have you compared these two different approaches?

Best wishes,
Lucy

**Comment by emdann** [comment]
Hi @lucygarner , we recommend doing both! The integration makes sure that the KNN graph captures cell states and not batch effects, and then adding the batch covariate makes sure that you don't call false positives because of local incomplete batch correction.

**Comment by lucygarner** [comment]
Hi @emdann, OK thank you. That is not something I had considered! I will give it a go.

**Comment by MikeDMorgan** [comment]
Hi @lucygarner I'm just closing this issue - feel free to re-open if Emma's suggestion didn't fix the problem.
