### ISSUE TITLE
testNhoods() returns :Error in glmFit.default(y, design = design, dispersion = dispersion, offset = offset,  :    NA dispersions not allowed

### ISSUE THREAD

**Issue by zzzzjb** [MarioniLab/miloR#291]
**Describe the bug**
Hi guys! Thanks a lot to develop the tools. I have a problem when I run the code:testNhoods(milo.obj, design=  ~ group, design.df = milo.design). It returns: 
Using TMM normalisation
Error in glmFit.default(y, design = design, dispersion = dispersion, offset = offset,  : 
  NA dispersions not allowed
In addition: Warning message:
In estimateDisp.default(y = y$counts, design = design, group = group,  :
  No residual df: setting dispersion to NA

## This is my code and data.
#creat milo 
sce_milo <- as.SingleCellExperiment(sce)
milo.obj <- Milo(sce_milo)
![image](https://github.com/MarioniLab/miloR/assets/145214852/9b8b69d6-e26a-4bae-99bb-da998959602c)

#Build a graph and neighbourhoods
milo.obj <- buildGraph(milo.obj, k=20, d=30)
milo.obj <- makeNhoods(milo.obj, k=20, d=30, refined=TRUE, prop=0.1)

#Calculate distances, count cells according to an experimental design and perform DA testing
milo.obj <- countCells(milo.obj, meta.data = data.frame(colData(milo.obj)), samples="sample")

milo.design <- data.frame(colData(milo.obj))[,c("sample", "group")]
milo.design <- distinct(milo.design)
rownames(milo.design) <- milo.design$sample
## Reorder rownames to match columns of nhoodCounts(milo)
milo.design <- milo.design[colnames(nhoodCounts(milo.obj)), , drop=FALSE]
milo.design
![image](https://github.com/MarioniLab/miloR/assets/145214852/30282098-f286-49bc-b48d-7bed8cbfe15a)

milo.obj <- calcNhoodDistance(milo.obj, d=30)
results <- testNhoods(milo.obj, design=  ~ group, design.df = milo.design)
![image](https://github.com/MarioniLab/miloR/assets/145214852/547a45db-dc20-41f4-8135-cbd64b9c9f76)
Thanks a lot to help me!

**Comment by bonaguidilab** [comment]
same question!  How did you deal with it?

**Comment by MikeDMorgan** [comment]
What does the distribution of nhood counts look like in your data? If the estimated dispersions are NA then it suggests you probably have extremely small nhoods.

**Comment by bonaguidilab** [comment]
> What does the distribution of nhood counts look like in your data? If the estimated dispersions are NA then it suggests you probably have extremely small nhoods. 
Thank you so much for your reply!!!
I've attached my nhoodcount distribution.  Would this distribution considered an extremely small nhoods? 
![image](https://github.com/MarioniLab/miloR/assets/80128836/440f5ff7-2e0f-42da-8f03-f65c89b26b5a)

**Comment by MikeDMorgan** [comment]
The guidance is to have a minimum of S*5 counts per nhood, where `S` is the number of samples in your analysis. Do you only have 4 samples and 4 groups? If that is the case, then you don't have any replicates per group, and hence you can't do any DA testing.
