### ISSUE TITLE
when should buildGraph be used with transposed=TRUE?

### ISSUE THREAD

**Issue by noranekonobokkusu** [MarioniLab/miloR#294]
Hi,

It seems the `buildGraph`'s help page states that `transposed` should be set to `TRUE` whenever one specifies the `d` parameter, but the provided tutorials do not do that. When the `transposed` argument should be set to `TRUE` then?

Thanks,
Ksenia

**Comment by MikeDMorgan** [comment]
Thanks for highlighting the lack of clarity - the information is contained in the `d` argument information:

```
The number of dimensions to use if the input is a matrix of cells X reduced
dimensions. If this is provided, transposed should also be set=TRUE.
```

Therefore `transposed=TRUE` is only relevant when the input is NOT a `SingleCellExperiment` or `Milo` object, i.e. a matrix of reduced dimensions. If you are using a `SingleCellExperiment` or `Milo` object as input then you can ignore the `transposed` argument.

**Comment by noranekonobokkusu** [comment]
Thank you, I see. So when I use the 'harmony' slot of the Milo object as a `reduced.dim`, it still is in the correct format and shouldn't be transposed? I was kind of surprised that it works both with and without `transposed=T`, even though the transposed harmony matrix should have conflicting dimensions with the rest of the object like annotations.

**Comment by MikeDMorgan** [comment]
The `reduced.dim` argument just tells the function which slot in `reducedDim` to use for graph-building. If you input a matrix of cells x reduced dimensions then you would need to use `transposed=TRUE`.

**Comment by noranekonobokkusu** [comment]
Thank you!
