### ISSUE TITLE
findNhoodGroupMarkers: overlapping nhoods in fake.meta

### ISSUE THREAD

**Issue by gianfilippo** [MarioniLab/miloR#296]
Hi,

I was looking at your function, findNhoodGroupMarkers, and noticed that when you assemble the fake.meta data frame, 
    for (i in seq_along(nhood.gr)) {
        nhood.x <- which(nhs.da.gr == nhood.gr[i])
        nhs <- nhs[rowSums(nhs) > 0, ]
        nhood.gr.cells <- rowSums(nhs[, nhood.x, drop = FALSE]) > 0
        fake.meta[nhood.gr.cells, "Nhood.Group"] <- ifelse(is.na(fake.meta[nhood.gr.cells, "Nhood.Group"]), nhood.gr[i], NA)
    }

here, after every iteration, the "Nhood.Group" for cells from overlapping nhoods gets overwritten, making the final "Nhood.Group" dependent on the ordering of nhood.gr, everything else being fixed.

Is this not going to affect the results ?

Thanks

**Comment by MikeDMorgan** [comment]
Hi @gianfilippo this is a necessary evil as cells can be members of multiple groups and nhoods. Therefore the GLM used for DGE cannot have the same cells included multiple times as it would violate the independence assumption. Even with multiple cells contributing to the mean expression of several nhoods this would artificially lower the variance of the mean. In practise, the overwriting of nhood group assignment for cells likely has little impact, though we have not tested this rigorously.

**Comment by gianfilippo** [comment]
Thanks!
