### ISSUE TITLE
plotNhoodSizeHist not lining up with nhoodCounts

### ISSUE THREAD

**Issue by LinearParadox** [MarioniLab/miloR#301]
When I run ```plotNhoodSizeHist(adata_milo)``` I get the following histogram, giving the smallest neighborhood as having less than 40 cells:

![plot](https://github.com/MarioniLab/miloR/assets/94434172/0c1ddcb0-f321-4b42-81db-f7fa25e38037)

However, when I run ```min(rowSums(nhoodCounts(adata_milo)))``` I get 54. 

Is plotNhoodsize plotting something different than the actual counts for the neighborhood?

**Comment by MikeDMorgan** [comment]
Hi @LinearParadox without your processing code up until this point it's tricky to determine if this is a genuine bug or not. Please post your working code and output of sessionInfo(). Thanks.

**Comment by LinearParadox** [comment]
Thanks for your response! I think it's actually some weird R behavior. When I just manually add up a row, I get the right result, but rowSums seems to consistently give a greater result. Thank you again!
