### ISSUE TITLE
Use milo with continuous variable

### ISSUE THREAD

**Issue by RunyuXia** [MarioniLab/miloR#302]
Hi! I have a dataset consisting of 19 samples with ages ranging from 8 to 95 weeks. Some time points have multiple samples while some only have one. In this case, would it be appropriate to use the testNhoods function with age as a continuous covariate? I tried running the algorithm with code

milo.res <- testNhoods(milo, design = ~Age, design.df = design_df, reduced.dim='scvi', fdr.weighting="graph-overlap") 

but the code ran for a very long time (>5 hrs) and I had to kill the program.

**Comment by MikeDMorgan** [comment]
Hi @RunyuXia - please provide the full analysis code for your analysis, including the output of sessionInfo(). The running time suggests that you haven't run makeNhoods with the `refinement_scheme="graph"`.
