### ISSUE TITLE
Seeking Guidance on Input Data for PCA Reduction and Gene Expression in Milo

### ISSUE THREAD

**Issue by tim-meese** [MarioniLab/miloR#315]
Hello developers of Milo,

Thank you for creating this intriguing tool for differential abundance testing in a clustering-free approach. I appreciate the effort you have put into developing it.

Regarding the vignette titled “Differential abundance testing with Milo - Mouse gastrulation example,” I have a question. 
The vignette states: “This dataset has already been pre-processed and contains a `pca.corrected` dimensionality reduction, which was built after batch correction using `fastMNN`.”

Here is my understanding: The different batches were integrated using `fastMNN`, and subsequently, a PCA was applied to that correction. Is this correct? I assume that the `pca.corrected` values were then used to construct the KNN graph. However, I want to check if understood it correctly as I am more familiar with Seurat's workflow.

I followed the integration steps as described in OSCA (Open Single-Cell Analysis), but when examining the `fastMNN` output, I noticed that it has the same number of genes as the number of highly variable genes. However, in the Milo vignette, there appear to be more genes. Could you provide some guidance on this discrepancy?

My intuition suggests that I should combine the raw/normalized expression for all the genes with the PCA reduction performed after integration. Is this the correct approach?

I eagerly await your response.

With kind regards,
Tim

**Comment by emdann** [comment]
Hi @tim-meese,

> Here is my understanding: The different batches were integrated using fastMNN, and subsequently, a PCA was applied to that correction. Is this correct? 

The data used in this vignette comes from [this paper](https://www.nature.com/articles/s41586-019-0933-9#Sec7), as processed in the MouseGastrulationData Bioconductor package (more info on datasets [here](https://bioconductor.org/packages/release/data/experiment/vignettes/MouseGastrulationData/inst/doc/MouseGastrulationData.html))

> I assume that the pca.corrected values were then used to construct the KNN graph. However, I want to check if understood it correctly as I am more familiar with Seurat's workflow.

That's right!

> I followed the integration steps as described in OSCA (Open Single-Cell Analysis), but when examining the fastMNN output, I noticed that it has the same number of genes as the number of highly variable genes. However, in the Milo vignette, there appear to be more genes. Could you provide some guidance on this discrepancy?

Again, check the MouseGastrulationData reference to clarify this: here the authors processed the data to get batch-corrected dimensions (`pca.corrected`) using HVGs, but then saved the object with all genes for other types of downstream analyses.

>My intuition suggests that I should combine the raw/normalized expression for all the genes with the PCA reduction performed after integration. Is this the correct approach?

We recommend minimizing differences between samples/batches in the latent dimensions used to build the KNN graph with whichever integration method you think works best for your dataset (FastMNN is one, but you could also use scVI, Seurat CCA, Harmony etc...). Depending on the experimental design of your dataset different integration methods have different advantages and drawbacks.

**Comment by tim-meese** [comment]
Hi @emdann 

Thank you so much for the prompt and comprehensive response. I truly appreciate it!

> We recommend minimizing differences between samples/batches in the latent dimensions used to build the KNN graph with whichever integration method you think works best for your dataset (FastMNN is one, but you could also use scVI, Seurat CCA, Harmony etc...). Depending on the experimental design of your dataset different integration methods have different advantages and drawbacks.

Alright, I plan to create an object containing the raw counts from my experiment, compute the log-normalized values using `scuttle`, and incorporate the latent dimensions of the cells that I previously derived using Seurat’s CCA to construct the KNN graph. Based on your guidance, this appears to be the correct approach. Furthermore, this should enable me to compare the results from Milo with the differential abundance I computed for the manually annotated clusters.

With kind regards
Tim
