### ISSUE TITLE
Inconsistent Default Values Between Functions

### ISSUE THREAD

**Issue by DarioS** [MarioniLab/miloR#319]
buildGraph: d = 50, makeNhoods: d = 30, calcNhoodDistance; d is missing. User should get consistent behaviour if left blank.

```r
> MILOdata <- calcNhoodDistance(MILOdata) # Other two functions have default value and don't error if missing.
Error in FUN(X[[i]], ...) : argument "d" is missing, with no default
```

**Comment by MikeDMorgan** [comment]
calcNhoodDistance has been superseded  - the function is not deprecated for backwards compatibility. Users should use `refinement_scheme="graph"` in `makeNhoods` and `fdr.weighting="graph-only"` in `testNhoods`.

**Comment by DarioS** [comment]
The vignette for version 2 still illustrates `calcNhoodDistance`. Can you please update the best practices to match the software? Also, did you intend to write `graph-overlap` rather than `graph-only`? It does not appear to be a valid parameter value.

```r
Error in graphSpatialFDR(x.nhoods = nhoods(x), graph = graph(x), weighting = fdr.weighting,  : 
  Weighting option not recognised - must be either k-distance, neighbour-distance, max or graph-overlap
```
