### ISSUE TITLE
Can't interpret plotNhoodGraphDA and plotUMAP

### ISSUE THREAD

**Issue by giuditta2024** [MarioniLab/miloR#320]
Hi all!
First of all, I would like to thank you for producing this useful tool.

I already went through other issues, but I did not find any other that could solve my problem.

I'm working with a dataset of cells with different genotypes for a variant (WT, homozygous, heterozigous, 80bp deletion, 16bp deletion) each captured at different timepoints (24h, 48h, 72h, 96h). 

I tested, for instance, each timepoint against all the others, like this, to compare the first timepoint 24 h versus all the others:
```
model <- model.matrix(~ 0 + timepoint, data=adata_design)

ave.contrast <- c("timepoint24h - (timepoint48h + timepoint72h + timepoint96h)/3")

mod.constrast <- makeContrasts(contrasts=ave.contrast, levels=model)

da_results <- testNhoods(adata_milo, 
                         design = ~ 0 + timepoint, 
                         design.df = adata_design, 
                         model.contrasts = ave.contrast, 
                         fdr.weighting="graph-overlap")
```

And then visualized like that: 
```
adata_milo <- buildNhoodGraph(adata_milo)

plotUMAP(adata_milo, colour_by="Assigned_GFPgenotype") + 
   plotNhoodGraphDA(adata_milo, da_results, alpha=0.1) +
  plot_layout(guides="collect" )
```

<img width="533" alt="image" src="https://github.com/MarioniLab/miloR/assets/111643904/c9e45aad-1eb9-46d5-b9b1-e18184af62c1">

In this first example above I colored the UMAP by **genotype** and I assumed that since the Nhoods in dark blue (positive logFC) are overlapping with the 16bp deletion genotype, the cells with 16bp del are more abundant in the timepoint 24h. Is that correct or am I assuming something wrong? 

Then, once I test for other timepoint, for istance the timepoint 96 h vs all the others, the results are more confused:

```
model <- model.matrix(~ 0 + timepoint, data=adata_design)
ave.contrast <- c("timepoint96h - (timepoint24h + timepoint48h + timepoint72h)/3")
mod.constrast <- makeContrasts(contrasts=ave.contrast, levels=model)

da_results <- testNhoods(adata_milo, 
                         design = ~ 0 + timepoint, 
                         design.df = adata_design, 
                         model.contrasts = ave.contrast, 
                         fdr.weighting="graph-overlap")
adata_milo <- buildNhoodGraph(adata_milo)

plotUMAP(adata_milo, colour_by="Assigned_GFPgenotype") + plotNhoodGraphDA(adata_milo, da_results, alpha=0.1) +
  plot_layout(guides="collect" )
```
<img width="538" alt="image" src="https://github.com/MarioniLab/miloR/assets/111643904/f00a947f-a985-4fd4-ae8a-0c5672f9fe70">

So in this case I cannot understand which genotype is more responsible for the shift here. 

I apologize in advance for the very naive question, I hope I did not misintepret completely the task. 

Thank you!

**Comment by MikeDMorgan** [comment]
You can annotate the nhoods based on single-cell level meta-data using `annotateNhoods`. You can then visualise the distribution of the LFCs using `plotDAbeeswarm` to give you an intuition about the relationships between your results and genotypes.

**Comment by giuditta2024** [comment]
Thank you!
