### ISSUE TITLE
Applicability to Cancer Samples

### ISSUE THREAD

**Issue by DarioS** [MarioniLab/miloR#322]
Have you considered the applicability of Milo to cancer cell data? I notice in the journal article a variety of scenarios (e.g. cirrhotic liver, thymus), but not cancer. I suppose that it is because one person's cancer clone is quite different to another's. For example,

> Epithelial cells, fibroblasts, endothelial cells, lymphocytes, and myeloid cell states contained a finite number of minor cell states, which were also reproducibly found in different patients. This was in stark contrast to the **tumor cell states** from the same group of patients, which were **largely patient-specific**.

Source: [CXCL9:SPP1 Macrophage Polarity Identifies a Network of Cellular Programs that Control Human Cancers](https://www.science.org/doi/abs/10.1126/science.ade2292), _Science_.

I have seen other researchers using it on cancer cell data, but I think it is a misuse of MiloR because it often ends up as one neighbourhood group being comprised of one patient's cells. Is it perhaps worth an explanatory paragraph in vignette?

**Comment by MikeDMorgan** [comment]
Hi @DarioS Milo is a general tool for differential abundance analysis. There could be many reasons for many tumour cell states being patient specific, and these could be biological or technical reasons. There is no reason why Milo can't be used for analysing cancer data _as long as the assumptions are reasonably met_. This is not specific to cancer data, but any data set that an analyst wishes to apply Milo to.

**Comment by DarioS** [comment]
O.K. For instance, how should one analyse [A Multi-modal Single-cell and Spatial Expression Map of Metastatic Breast Cancer Biopsies Across Clinicopathological Features](https://www.nature.com/articles/s41591-024-03215-z), _Nature Medicine_, [SCP2702](https://singlecell.broadinstitute.org/single_cell/study/SCP2702)? Cancer cells cluster almost entirely by patient.

> Although non-malignant cells clearly grouped by cell type across biopsies, malignant cells grouped first by patient, as previously described in scRNA-seq of solid tumors, consistent with diverse patterns of inferred copy number aberrations.

![image](https://github.com/user-attachments/assets/3c7813c9-9619-467e-959a-24dddf8c3768)

Milo basically detects lots of neighbourhoods that have cells from only one individual, hence one artefactual phenotype.

![image](https://github.com/user-attachments/assets/408cf057-eda6-418a-be4a-e667b6721e10)

**Comment by MikeDMorgan** [comment]
As I said, if the assumptions of Milo are met, then there should be no issue. Clearly in this dataset the assumption that cells from samples are intermingled doesn't hold up, so it wouldn't be appropriate unless you can find a way to build a NN-graph where cells from samples are mixed in neighbourhoods.

**Comment by yulijia** [comment]
Hi @MikeDMorgan, could you please let me know all the assumptions that need to be met before applying miloR to the datasets? I believe one assumption might be that the data should be intermingled.
