### ISSUE TITLE
GLMM vignette

### ISSUE THREAD

**Issue by CarrieMeeks** [MarioniLab/miloR#323]
I have been heavily referring to the glmm vignette. But it now has a 404:error message. Will an updated glmm vignette be posted soon?

**Comment by MikeDMorgan** [comment]
Hi @CarrieMeeks Could you be more specific please? How are you access the vignette? Is it via the Bioconductor website, inside Rstudio, etc?

**Comment by MikeDMorgan** [comment]
FYI - I've updated the link to go directly to BioConductor, so this should work now.

**Comment by CarrieMeeks** [comment]
Thank you for fixing the link!
