### ISSUE TITLE
Prevention of Neighbourhood Merging of Similar Cell Types into Neighbourhood Groups

### ISSUE THREAD

**Issue by DarioS** [MarioniLab/miloR#326]
I notice that neighbourhood groups will make groups of different cell types if cell types are similar. Might Milo accept some per-cell labelling from a method such as SingleR to set up a boundary not to be crossed for neighbourhood merging? For example,

![image](https://github.com/MarioniLab/miloR/assets/631218/327ddeeb-5ca4-45fb-b3c2-5d282156e8d0)

Source: [Cancer-associated Fibroblast Classification in Single-cell and Spatial Proteomics Data](https://www.nature.com/articles/s41467-023-39762-1), _Nature Communications_

The graph of such a data set would be highly connected, meaning that heterogeneous neighbourhood groups are formed.

![image](https://github.com/MarioniLab/miloR/assets/631218/0871c998-dde4-40ac-863c-aef82fe1f34a)

A split plot shows the true extent of the overlap (in two dimensions) and rampant overlplotting of dots in the overall plot.

**Comment by MikeDMorgan** [comment]
The function is purely for grouping neighbourhoods based on the neighbourhood adjacency matrix. It does not aim to recapitulate single-cell clustering/annotation.
