### ISSUE TITLE
Does MiloR take into account that the two compared conditions have different number of cells?

### ISSUE THREAD

**Issue by crodriguezres** [MarioniLab/miloR#335]
Hi! Thanks for your great tool!
Just to double check: Does MiloR take into account that we can be giving two conditions with different sample size. For example condition A has 1000 cells and condition B has 100000 cells to do the differential abundance analysis?
Thanks in advance!

**Comment by DarioS** [comment]
I am just a user of the Milo package, but I think that Milo will not correctly model such a data set.

> Under the assumption that the majority of neighbourhoods are not differentially abundant ...

**Comment by MikeDMorgan** [comment]
Hi @crodriguezres - the short answer is yes, up to a point. The TMM normalisation factors used in the NB-GLM and NB-GLMM seek to account for imbalances in the number of cells across samples. However, if all of condition A have ~1000 cells and all of B have ~100000 cells, then there is no guarantee that the results will not be driven by this difference (one order of magnitude _might_ be OK, but you would need to evaluate this in your analysis).

If there are big differences in the numbers of cells, but not 100% confounded with your experimental design as you describe, the issue should be less severe. If you are concerned, then inspect the MA plots and look for a large deviation of from the expected median LFC of 0. `plotNhoodMA` can assist here.
