### ISSUE TITLE
Log10 FC or Log2 FC?

### ISSUE THREAD

**Issue by mainharryHR** [MarioniLab/miloR#336]
Dear MilloR team,

I know in the paper, it is clearly claimed Log FC (= Log10 FC), I am writing to confirm that it is not Log2 FC?. 
If we see LogFC=3, it means there are 1000 differences, which sounds a lot to me :).

Many thanks for the nice package.

Best,
Nic

**Comment by MikeDMorgan** [comment]
Hi @mainharryHR It is the natural log, not base 10 or 2, so a LFC=3 is a fold-change of exp(3) $\approx$ 20.

**Comment by elise-smith** [comment]
Hi @MikeDMorgan 

This thread suggests that the natural log is being used, but a previous thread suggested first that they are natural log and then that they are log2.

Please could you let me know what you were referring to here?
https://github.com/MarioniLab/miloR/issues/81#issuecomment-916709986

Thank you!

**Comment by MikeDMorgan** [comment]
@elise-smith Sorry for the confusion - the Milo2.0 GLMM reports on a natural log scale while the GLM (edgeR) reports on a log2FC - this needs to be resolved by me. Thanks for highlighting.

**Comment by MikeDMorgan** [comment]
Yes that is correct.
