### ISSUE TITLE
Direction of test for logFC calculation 

### ISSUE THREAD

**Issue by RemiDL** [MarioniLab/miloR#338]
Hi, 

I'm wondering if there is a way to check the direction of the test used to get the LogFC.
I have a seurat object converted to sce, then I run Milo pipeline and run the differential abundance per group:

da_results <- testNhoods(traj_milo, design = ~ group, design.df = traj_design_order)

The outcome is clear that I have neighborhood with positive or negative LogFC, but I can'T be sure of the direction of the test.
Can I find this information in the design.df or somewhere in the milo object ?

Thanks a lot for your help.
Best regards
Rémi

**Comment by MikeDMorgan** [comment]
The direction is set by the variable in your model. By default in R this is lexicographical ordering - you can set the explicit direction/compator using a factor variable.
