### ISSUE TITLE
Existence of 2 tuitorials for the "Differential abundance testing with Milo - Mouse gastrulation example"

### ISSUE THREAD

**Issue by JesseRop** [MarioniLab/miloR#339]
Dear developers,

Thank you very much for the great package. I see 2 tutorial for the "Differential abundance testing with Milo - Mouse gastrulation example". Here https://rawcdn.githack.com/MarioniLab/miloR/7c7f906b94a73e62e36e095ddb3e3567b414144e/vignettes/milo_gastrulation.html  and here https://www.bioconductor.org/packages/devel/bioc/vignettes/miloR/inst/doc/milo_gastrulation.html
Just want to know if these are identical?

thanks,
Jesse

**Comment by MikeDMorgan** [comment]
Hi @JesseRop Those 2 URLS are the same link - did you mean to C&P different links?

**Comment by JesseRop** [comment]
Hi @MikeDMorgan , this is the other link https://www.bioconductor.org/packages/devel/bioc/vignettes/miloR/inst/doc/milo_gastrulation.html  . I have edited the original message above as well

**Comment by MikeDMorgan** [comment]
The date on the latter is more recent, hence it is more up to date.
