### ISSUE TITLE
No Significant Neighbourhoods Result is Error

### ISSUE THREAD

**Issue by DarioS** [MarioniLab/miloR#342]
Shouldn't it simply be a message and not an error? Finding no statistically signficant differences seems like a valid outcome to me.

```r
>  groupNhoods(MILOdata, smokerResults)
Error in groupNhoods(MILOdata, smokerResults) : 
  No DA neighbourhoods found
```
The model specified was `~ Smoker + (1|SampleID)`

**Comment by MikeDMorgan** [comment]
If you set `da.fdr=0.1` you can achieve the desired result, i.e. cluster nhoods without any statistically significant DA nhoods.
