### ISSUE TITLE
Gene expression testing of only DA neighborhoods within group??

### ISSUE THREAD

**Issue by carl-coyle** [MarioniLab/miloR#345]
Hi there, 

Just a query regarding the functionality of FindNhoodGroupMarkers and testDiffExp. 

My understanding is that when we group together neighborhoods using groupNhoods the aggregated output group is a mixture of neighborhoods which are differentially abundant and not differentially abundant from the results of testNhoods??. 
Then when we do FindNhoodGroupMarkers it compares cells within the whole neighborhood group (belonging to both DA and non DA neighborhoods) to cells within other neighborhood groups.

Apologies if my interpretation of this is incorrect. But on the assumption that it is, then both FindNhoodGroupMarkers and testDiffExp doesn't actually give any information as to the specific DA neighborhoods themselves but rather a gene signature for a mixture of DA and non-DA neighborhoods. 

Is there a way to define the gene signature only for the DA neighborhoods in a group? I ask this question on the assumption that those DA neighborhoods are a sub cellular state within the aggregated group thus they would have a transcriptional profile distinct from that of the non-DA neighborhoods. maybe that's not correct though?

For example when I group my neighborhoods after analysis I get the following (see below image). The neighborhood group 3 is of interest but you can see that only a proportion of the neighborhoods in that group are actually differentially abundant. It would be interesting to be able to compare the gene signature of only these DA neighborhoods. That way we are describing the gene signature for the specific population of neighborhoods which are DA rather than a combination of DA and non-DA neighborhoods. 

In addition, is it possible to extract the lognormcount values for a selected gene across all samples so as to compare how the expression levels on a per sample basis look across groups after doing testDiffExp. For example after doing testDiffExp on Unstimulated versus Stimulated I find it useful to show that the increased gene expression within one of the groups is reflected in the majority of samples within that group rather than being influenced by a couple of strong outliers.

![image](https://github.com/user-attachments/assets/a2027172-ecf6-415f-a317-7ae58fc0ecde)

**Comment by MikeDMorgan** [comment]
Hi @carl-coyle `testDiffExp` tests _within_ an nhood group according to an experimental design, e.g. if you compared patients v.s controls for your DA testing, you can compare patients vs. controls for DGE within each nhood group. `FindNhoodGroupMarkers` is the only function that identifies DEGs _between_ nhood groups.

Bear in mind that the DA nhoods are the ones that have been identified given a statistical threshold, i.e. spatial FDR cut-off. If you want to compare DA vs. non-DA within a group then I'd recommend you regress gene expression on DA LFC within each nhood group. You can use the nhoodExpression matrix for this and set it up using limma. Also note that the nhoods have overlapping cells and so are not independent, so there might be some over-inflation of test statistics. You can review this by randomly shuffling the LFC, say 100 times, and compute the number of times you get a DGE result for each gene. With these you can then make a Q-Q plot to check for departure from the null expectation for a random set of genes <- I'd select these across the range of low, medium, highly expressed genes.

**Comment by carl-coyle** [comment]
That makes sense. Thank you for your prompt response. Is it also possible to extract the information as per below? Apologies if it seems rather straightforward to do, I'm still finding my way with bioinformatics. 

"In addition, is it possible to extract the lognormcount values for a selected gene across all samples so as to compare how the expression levels on a per sample basis look across groups after doing testDiffExp. For example after doing testDiffExp on Unstimulated versus Stimulated I find it useful to show that the increased gene expression within one of the groups is reflected in the majority of samples within that group rather than being influenced by a couple of strong outliers."

**Comment by MikeDMorgan** [comment]
You need to compute the pseudobulk expression for each sample, split by cluster/group/nhood depending on what level you want to summarise the expression data. I recommend you iterate over your nhoods and extract the single cells contained in it, then given you know which cells come from which experimental sample, calculate the average expression for the cells in that nhood for each sample. Wash and repeat for each nhood.

**Comment by MikeDMorgan** [comment]
If your issue persists, please re-open. Closing otherwise.
