### ISSUE TITLE
Subsetting the dataset for DA testing

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloR#56]
It would be useful to incorporate a subsetting option in `testNhood` to exclude some samples in the DA analysis, basically excluding some samples from the count matrix and design matrix. 

For example, a colleague is testing out Milo on a dataset where she wants to test for differences in abundance with age, but the big dataset includes a few samples that were FACS sorted differently, and DA in that subset is not of interest. 

The best solution would be of course to exclude those samples at the beginning and rebuild all the graph, neighbourhoods etc, but this might be time consuming for a big dataset if you just want to do a quick check. 

Would this be completely accounted for by adding a nuisance covariate in the design? Or would having a subsetting make interpretation easier?

**Comment by MikeDMorgan** [comment]
Strictly you can do this if you have a single variable that contains your variable of interest _and_ the samples you don't want, then you can use model contrast to compare the relevant groups. That only really works for categorical/factor variables though. If it's a continuous variable that's harder to do, so sub-setting might make sense.

I would be quite concerned about including samples in the graph and neighbourhood construction that are not relevant to the DA testing at all - these samples __will__ affect the graph structure and connectivity, so the best practise solution would be to remove them and rebuild the graph.

**Comment by emdann** [comment]
I agree the way to go should be making a new graph. I'll keep this open for now, in case it becomes a frequently requested feature, but shouldn't be high priority.

**Comment by MikeDMorgan** [comment]
I've started on the solution for this by allowing a `design.df` to be passed to `testNhoods` where the rownames are a strict subset of the colnames of `nhoodCounts`: #109 

I'm not sure if it completely allows this behaviour yet - it'll need proper road-testing.

**Comment by MikeDMorgan** [comment]
This feature should now be implicit by passing a meta data frame whose rownames are a subset of the colnames of the `nhoodCounts` slot.
