### ISSUE TITLE
New bug in FindNhoodMarkers

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloR#65]
I was rerunning the liver analysis script, after reinstalling the latest `miloR` version, and I get an error I am not sure how to debug. Running:
```
nhood_markers <- findNhoodMarkers(liver_milo, milo_res, overlap=1, return.groups = TRUE,
                                  subset.row = endo_hvgs,
                                  subset.nhoods = str_detect(milo_res$annotation_indepth, "Endo"))

```

I get:
```
Error in UseMethod("isSymmetric") : no applicable method for 'isSymmetric' applied to an object of class "c('double', 'numeric')"
```

The traceback says the problem is in 
```
.group_nhoods_from_adjacency(nhoods(x), nhood.adj = nhoodAdjacency(x), da.res = da.res, is.da = da.res$SpatialFDR < da.fdr, merge.discord = merge.discord, overlap = overlap, subset.nhoods = subset.nhoods)
```

Any ideas?

**Comment by MikeDMorgan** [comment]
You need to set `compute.new=TRUE` in `findNhoodMarkers` <- the issue stems from having an older Milo object that doesn't have the proper `nhoodAdjacency` slot.

**Comment by emdann** [comment]
I'll try, but I just remade the Milo object w the new version...

**Comment by emdann** [comment]
It works with `compute.new`, but I am not sure what went wrong with building the Milo object.

**Comment by MikeDMorgan** [comment]
Hmm, OK - I'll leave this issue open to remind me to debug this one.
