### ISSUE TITLE
Overplotting in nhood graphs

### ISSUE THREAD

**Issue by MikeDMorgan** [MarioniLab/miloR#67]
The `plotNhoodGraphDA` can be hard to interpret when there is a high density of neighbourhoods. Example:
![Lymphoid_milo_CntrlVsMild-DAnhood-UMAP](https://user-images.githubusercontent.com/6473398/97585192-c4d3ea80-19f0-11eb-85dc-af93ed81f576.png)

It might be worth plotting 2 layers: 1) Non-DA neighbourhoods (white fill), 2) DA neighbourhoods (coloured by LFC). That way the DA neighbourhoods are never obscured by the non-DA neighbourhoods.

**Comment by emdann** [comment]
- use `ggraster` to make this faster for when you have a lot of edges
- Add option to remove the edges

**Comment by ryandikdan** [comment]
Have either of these been implemented? I'm working with a very large dataset and I can't get it to give me an output at all.

**Comment by MikeDMorgan** [comment]
Hi @ryandikdan This turns out to be some what time-consuming because the plotting engine uses ggnetwork, so it's fallen down the priority list. In the interim - if you have lots of very dense overlapping neighbourhoods then I would recommend using a larger `k` and a smaller `prop` in `makeNhoods` and `buildGraph` to alleviate the problem for now.

**Comment by ryandikdan** [comment]
Thanks, I'll give that a shot, but wouldn't a higher k create more edges?

**Comment by MikeDMorgan** [comment]
The combination of a larger `k` and smaller `prop` should create fewer nhoods, which will then reduce the total number of edges that need plotting. It's not an ideal solution I agree; perhaps this is the push needed to actually fix the large data set plotting.

**Comment by ryandikdan** [comment]
Haha, glad to be the one pushing. If there's anything I can do to help let me know!
