### ISSUE TITLE
Dealing with few cells from a sample 

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloR#69]
I was running `testNhoods` on a small dataset and I got this error message:
```r
Error in DGEList(counts = nhoodCounts(x)[keep.nh, ], lib.size = log(colSums(nhoodCounts(x)))) : 
  negative library sizes not permitted
```
The problem is that the cells of a one sample are not captured in any neighbourhood. 

The quick (and probably the proper) fix is to remove this sample with very few cells from testing, but I think at least an error message here or a warning when running `countCells` could be useful. Ideas?

**Comment by MikeDMorgan** [comment]
Tricky - I agree an informative error message is probably the simplest thing to do.
