### ISSUE TITLE
Problems with DGE testing using counts

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloR#75]
Running `findNhoodMarkers` setting `assay=counts` generates this error:

```r
Error in dimnames(x) <- dn : length of 'dimnames' [2] not equal to array extent
```
Traceback:
```r
3. | `colnames<-`(`*tmp*`, value = c("", "NGenes", "n.gene", "")) at testDiffExp.R#287
2. .perform_counts_dge(exprs, i.model, model.contrasts = i.contrast, gene.offset = gene.offset) at findNhoodMarkers.R#285
1. findNhoodMarkers(embryo_milo, da_results, assay = "counts", subset.nhoods = da_results$celltype == "Epiblast")
```
The issue arises when setting a gene offset:
https://github.com/MarioniLab/miloR/blob/0883cd587190499c3cef0c864c9be228b1e640d4/R/testDiffExp.R#L284-L288
 
`test.model` only has one column, so `colnames(test.model[, c(2:ncol(test.model))])` includes `NGenes` already.

The easy work-around is to set `gene.offset=FALSE`, but I am not super sure of the risks or of how the offset is used later in the DGE testing, since `NGenes` doesn't seem to be included in the design...

If setting the offset is not useful, it might be worth setting `gene.offset=FALSE` automatically if `assay="counts"`

**Comment by MikeDMorgan** [comment]
NGenes is incorporated into the model.matrix <- this is what is fed into edgeR for adjustment, so it does get used implicitly when `gene.offset=TRUE`.

I'm confused why your `test.model` only has a single column <- it should have at least 2: 1) Intercept, 2) Condition.

**Comment by emdann** [comment]
Solved with https://github.com/MarioniLab/miloR/pull/80
