### ISSUE TITLE
Problems with .group_nhoods_from_adjacency

### ISSUE THREAD

**Issue by emdann** [MarioniLab/miloR#79]
1. The function renames the list of nhoods as indices, but the names in the nhood slot are usually the indices of the sampled cell
https://github.com/MarioniLab/miloR/blob/595566b2b3cba5ce1f92941e15b9bb5049ff7ef3/R/utils.R#L99-L102

This leads to wrong matching if the user provides `subset.nhoods` as indices 
https://github.com/MarioniLab/miloR/blob/595566b2b3cba5ce1f92941e15b9bb5049ff7ef3/R/utils.R#L106-L109

2. The function assumes that rows and columns in `nhoodAdjacency(x)` are in the same order as `nhoods(x)`, but I find this is often not the case. Is `nhoodAdjacency(x)` added just via `buildNhoodGraph` ? If that's the case it might be an issue with the reordering required for plotting.

**Comment by MikeDMorgan** [comment]
I will update the nhood grouping to make use of the nhoodGraph. Initially I'll use Louvain clustering as this _should_ provide modular clusters that are intuitive.

**Comment by MikeDMorgan** [comment]
Resolved in #96
