### ISSUE TITLE
Interaction testing in Milo

### ISSUE THREAD

**Issue by dylanmr** [MarioniLab/miloR#86]
Thanks for developing this really awesome package. 

I have been generating a single cell dataset, in which I have 11 time points and multiple conditions. I was wondering if it would be possible to implement an LRT test in milo to identify age:condition interactions which are DA in the graph. 

Thanks! 
Dylan

**Comment by MikeDMorgan** [comment]
Hi Dylan, If you want to test for a specific interaction, you can create a dummy variable that codifies the interaction, and test on that variable using `testNhoods`.

**Comment by dylanmr** [comment]
thanks for the quick answer! I had a feeling i was overthinking it. 

Dylan
