### ISSUE TITLE
Is there any tutorial/example for Python adata as input for miloR 

### ISSUE THREAD

**Issue by YubinXie** [MarioniLab/miloR#87]
Hi I am very interested in trying miloR but I am a Python user. I was wondering if there is any tutorials/example using adata as input for miloR. Thank you very much!

**Comment by emdann** [comment]
Hi @YubinXie, thank you for you interest in using our package. You can find an example jupyter notebook using conversion of anndata to R [here](https://github.com/MarioniLab/milo_analysis_2020/blob/main/notebooks/milo_in_python.ipynb).

**Comment by YubinXie** [comment]
Amazing thank you!!!

**Comment by liezeltamon** [comment]
Hi @emdann,

Thanks for the package! Do you have a tutorial for doing the mixed effect models in python? Thank you!
