### ISSUE TITLE
buildNhoodGraph speed ?necessary

### ISSUE THREAD

**Issue by bjstewart1** [MarioniLab/miloR#90]
Great tool - super useful.

I am finding buildNhoodGraph extremely slow and doesn't scale well with increasing dataset size. Presumably because it is trying to generate a dense adjacency matrix for all neighbourhoods...

As far as I can see this isn't strictly necessary for downstream analysis (correct me if I am wrong!!) and you could (perhaps just for larger datasets) plot the neighbourhoods according to their UMAP coordinates without the edges.

Perhaps needs 
`plotNhood`
 and 
`plotNhoodDA`
 plotting functions?

Hope that makes sense

**Comment by bjstewart1** [comment]
I suppose the alternative to this would be to rethink 
`buildNhoodGraph` 
as a KNN graph construction exercise between the representative cells?

Final thought is that 
`.build_nhood_adjacency` outputs the adjacency as the length of the intersect.
Have you considered instead using the jaccard distance between neighbourhoods?
so in: 
`.build_nhood_adjacency `

   ` pairs_int <- sapply( which(keep_pairs), function(x) length( intersect( nhoods[[nms[x,1]]], nhoods[[ nms[x,2] ]]) )/length( union( nhoods[[nms[x,1]]], nhoods[[ nms[x,2] ]]) )`

Just a thought....

**Comment by emdann** [comment]
I'm a bit weary of switching from intersection to JI since the matrix stored in the `nhoodGraph` slot is also used to group nhoods for the differential expression analysis functions. @MikeDMorgan any thoughts?

**Comment by bjstewart1** [comment]
yes fair enough if it is used downstream rather than just for aesthetic plotting...
look forward to the speed advantages with #93

**Comment by MikeDMorgan** [comment]
I'd rather keep the adjacency based on the number of overlapping cells between neighbourhoods, as this can be used to tune the nhood grouping - it's not clear how to necessarily translate that directly to a JI value. We can keep it in mind if we do want think about the adjacency/nhood grouping based on set operations though.

**Comment by emdann** [comment]
Speed issues addressed by https://github.com/MarioniLab/miloR/issues/73
