### ISSUE TITLE
How to use a kNN constructed by Seurat

### ISSUE THREAD

**Issue by ccruizm** [MarioniLab/miloR#95]
Good day!

Great tool! I am trying to implement it on my data but have not been able to make it work so far. I have analyzed my data using `Seurat`, normalized my data via `SCTransform`, and integrate the dataset with `FastMNN`. 
I exported my `Seurat` object to `SingleCellExperiment` and then create a `Milo` class object:
```
class: Milo 
dim: 20065 18326 
metadata(0):
assays(2): counts logcounts
rownames(20065): AL627309.1 AL669831.5 ... AL844908.1 AP001469.2
rowData names(6): sct.detection_rate sct.gmean ...
  sct.residual_variance sct.variable
colnames(18326): third-prettx_AAACCCACAACTGAAA-1
  third-prettx_AAACCCACAACTGTGT-1 ... second-posttx_TTTGTTGTCCACTTTA-1
  second-posttx_TTTGTTGTCGTAGTGT-1
colData names(11): orig.ident nCount_RNA ... SCT_snn_res.1 ident
reducedDimNames(2): MNN UMAP
altExpNames(0):
nhoods dimensions(2): 1 1
nhoodCounts dimensions(2): 1 1
nhoodDistances dimension(1): 0
graph names(0):
nhoodIndex names(1): 0
nhoodExpression dimension(2): 1 1
nhoodReducedDim names(0):
nhoodGraph names(0):
nhoodAdjacency dimension(2): 1 1
```
I tried to use the MNN reduction in `buildGraph`: 
```
sce_milo <- buildGraph(sce_milo, k = 30, d = 30, reduced.dim = "MMN")
```
and starts running with only the next output `Computing PCA - name not in slot` but never ends (so I guess I am not using the right reduction?). Next, I tried to use the precomputed KNN graph using the function `buildFromAdjacency`. For that I used the `seu_obj@graphs$SCT_snn` and ran the function but showed an error: 
```
Casting to sparse matrix format

Inferring k from matrix

Warning message in buildFromAdjacency(m):
“Row sums are not all equal, checking columns”
Error in buildFromAdjacency(m): Cannot infer k from matrix, please provide a value or check input
Traceback:

1. buildFromAdjacency(m)
2. stop("Cannot infer k from matrix, please provide a value or check input")
```
I would like to have your input in this matter and see what is the best way to work around it. Thanks in advance!

**Comment by emdann** [comment]
Hi @ccruizm 
There seems to be a typo in the name of the `reduced.dim` you pass to `buildGraph` (`"MMN"` and not `"MNN"`). If the function can't find the name of the reduced dim in the Milo object, it will try to run PCA on the full feature matrix.

**Comment by ccruizm** [comment]
Totally right, did not notice it! naive mistake. Thanks!
