### ISSUE TITLE
Minor error with countCells when using scanpy/anndata worflow

### ISSUE THREAD

**Issue by zktuong** [MarioniLab/miloR#98]
Hi,

just found a small compatibility error when interacting with scanpy/anndata due to how sometimes pandas's categorical don't play nice in R's data frame. It throws the following error:

```R
Error in meta.data[samples] == i.s : 
  comparison of these types is not implemented
```

This fixes the error start Line 68:

from
```R
if(!is.null(meta.data)){
        samp.ids <- unique(meta.data[, samples])
    } else{
        samp.ids <- unique(samples)
    }
```

to 

```R
if(!is.null(meta.data)){
        samp.ids <- unique(as.character(meta.data[, samples]))
    } else{
        samp.ids <- unique(samples)
    }
```

**Comment by MikeDMorgan** [comment]
Thanks Kelvin - strictly there should first be a check for the data type of `meta.data[, samples]`, and if not character or factor, then it can be cast to the appropriate format as you suggest. 

Do you want to put together a PR for this?

**Comment by zktuong** [comment]
Hi Mike, sure. 

I assume the preference is to respect factor levels first? Because uniques ignores the factor levels.

**Comment by MikeDMorgan** [comment]
Sure - generally we shouldn't expect factors thinking about it for sample levels, but just in case there is an errant `stringAsFactors=TRUE` is active somewhere we should use `levels` when appropriate - I'll reconcile the use of `unique`  and `levels` once you've made the PR.
